# Generated by Django 6.0.4 on 2026-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_brands',
                'ordering': ['-created_at'],
                'unique_together': {('company_id', 'branch_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_categories',
                'ordering': ['-created_at'],
                'unique_together': {('company_id', 'branch_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('warehouse_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('manager_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Storage capacity in sq ft or cubic meters', max_digits=12)),
                ('current_occupancy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address_line', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_warehouses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'branch_id'], name='inventory_w_company_059e76_idx'), models.Index(fields=['warehouse_name'], name='inventory_w_warehou_38e20b_idx'), models.Index(fields=['is_active'], name='inventory_w_is_acti_d0b90f_idx')],
                'unique_together': {('company_id', 'branch_id', 'code')},
            },
        ),
    ]
