# Generated by Django 6.0.4 on 2026-06-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('category_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('brand_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('product_type', models.CharField(choices=[('simple', 'Simple Product'), ('variable', 'Variable Product'), ('bundle', 'Bundle Product'), ('digital', 'Digital Product'), ('service', 'Service')], default='simple', max_length=20)),
                ('unit_of_measure', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('LTR', 'Liters'), ('MTR', 'Meters'), ('BOX', 'Box'), ('SET', 'Set'), ('PAIR', 'Pair'), ('DOZEN', 'Dozen')], default='PCS', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_price_from', models.DateField(blank=True, null=True)),
                ('special_price_to', models.DateField(blank=True, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_class', models.CharField(choices=[('standard', 'Standard Rate'), ('reduced', 'Reduced Rate'), ('zero', 'Zero Rate'), ('exempt', 'Exempt')], default='standard', max_length=20)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('main_image', models.URLField(blank=True)),
                ('gallery_images', models.JSONField(default=list)),
                ('video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'branch_id'], name='inventory_p_company_eae843_idx'), models.Index(fields=['sku'], name='inventory_p_sku_3b9fee_idx'), models.Index(fields=['category_id'], name='inventory_p_categor_4a3921_idx'), models.Index(fields=['brand_id'], name='inventory_p_brand_i_bc4ef6_idx'), models.Index(fields=['status'], name='inventory_p_status_b23ba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('attribute_group', models.CharField(blank=True, max_length=100)),
                ('is_filterable', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_product_attributes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('attribute_combination', models.JSONField(default=dict)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('main_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
            ],
            options={
                'db_table': 'inventory_product_variants',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(blank=True, null=True)),
                ('reorder_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('max_stock_level', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True)),
                ('location_bin', models.CharField(blank=True, max_length=50)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'inventory_stocks',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_tags',
                'indexes': [models.Index(fields=['company_id', 'branch_id'], name='inventory_t_company_d35243_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.tag')),
            ],
            options={
                'db_table': 'inventory_product_tags',
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='inventory_p_sku_ba022a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('product', 'variant', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='producttag',
            unique_together={('product', 'tag')},
        ),
    ]
