# Generated by Django 6.0.4 on 2026-06-14 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='images',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='branch_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='company_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('attribute_key', models.CharField(max_length=100)),
                ('attribute_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'inventory_variant_attributes',
                'indexes': [models.Index(fields=['attribute_key', 'attribute_value'], name='inventory_v_attribu_0a80e0_idx')],
                'unique_together': {('variant', 'attribute_key')},
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('image_url', models.CharField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'inventory_variant_images',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['variant', 'is_primary'], name='inventory_v_variant_680734_idx')],
            },
        ),
    ]
