# Generated by Django 6.0.4 on 2026-06-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_productattribute_productvariant_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='msrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price_from',
        ),
        migrations.RemoveField(
            model_name='product',
            name='special_price_to',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
    ]
