# Generated by Django 6.0.4 on 2026-06-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattribute',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='inventory.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('company_id', 'branch_id', 'attribute_key', 'attribute_value'), name='unique_catalog_attribute'),
        ),
    ]
