# Generated by Django 6.0.4 on 2026-06-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_customerinvoice_bank_account_and_more'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('CREDIT', 'Credit/On Account'), ('OTHER', 'Other')], default='CREDIT', max_length=20),
        ),
    ]
