# Generated by Django 6.0.4 on 2026-05-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_salesorder_customer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salesshipment',
            name='sales_shipm_sales_o_4098f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesshipment',
            name='sales_shipm_company_55e309_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesshipmentline',
            name='sales_shipm_shipmen_ed5bf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='salesshipmentline',
            name='sales_shipm_sales_o_2179b1_idx',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='expected_ship_date',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='quantity_shipped',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALE', 'Sale'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('ADD_STOCK', 'Add Stock'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('STOCK_TAKE', 'Stock Take'), ('INITIAL', 'Initial Stock')], max_length=30),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorderline',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='sales_order_line',
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='salesshipmentline',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='SalesShipment',
        ),
        migrations.DeleteModel(
            name='SalesShipmentLine',
        ),
    ]
