# Generated by Django 6.0.4 on 2026-05-21 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFieldChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('field_name', models.CharField(db_index=True, help_text='Name of the field that changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (as string)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (as string)', null=True)),
            ],
            options={
                'db_table': 'inventory_audit_field_changes',
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_entity__ff6b98_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='inventory_a_created_e6162c_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('BULK_CREATE', 'Bulk Create'), ('BULK_UPDATE', 'Bulk Update'), ('BULK_DELETE', 'Bulk Delete')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.UUIDField(db_index=True, help_text='UUID of the affected row'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(db_index=True, help_text="Model name (e.g., 'product', 'variant')", max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='reference_id',
            field=models.UUIDField(db_index=True, help_text='Reference ID (e.g., transaction_id, order_number)', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='source_module',
            field=models.CharField(default='inventory', help_text='Module that generated the audit', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_id',
            field=models.IntegerField(db_index=True, help_text='User ID who performed the action', null=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='idx_audit_entity'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company_id', 'branch_id', '-created_at'], name='idx_audit_tenant'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id', 'action', '-created_at'], name='idx_audit_user_action'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['created_at'], name='idx_audit_created_at'),
        ),
        migrations.AddField(
            model_name='auditfieldchange',
            name='audit_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='inventory.auditlog'),
        ),
        migrations.AddField(
            model_name='auditfieldchange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfieldchange',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfieldchange',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='after_state',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='before_state',
        ),
        migrations.AddIndex(
            model_name='auditfieldchange',
            index=models.Index(fields=['field_name'], name='idx_audit_field_name'),
        ),
        migrations.AddIndex(
            model_name='auditfieldchange',
            index=models.Index(fields=['audit_log', 'field_name'], name='idx_audit_log_field'),
        ),
    ]
