# Generated by Django 6.0.4 on 2026-06-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productvariant_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('SALE_SHIPMENT', 'Sale Shipment'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out'), ('ADJUSTMENT', 'Adjustment'), ('DAMAGE', 'Damage'), ('ADD_STOCK', 'Add Stock'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('STOCK_TAKE', 'Stock Take'), ('INITIAL', 'Initial Stock')], max_length=30),
        ),
    ]
