# Generated by Django 6.0.4 on 2026-06-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='rating',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
