# Generated by Django 6.0.4 on 2026-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_salesorderline_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnline',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity returned from this line'),
        ),
    ]
