# Generated by Django 6.0.4 on 2026-06-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_variantattribute_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Destination warehouse for received goods (not required for office inventory)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse'),
        ),
    ]
