# Generated by Django 6.0.4 on 2026-06-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_salesorder_bank_account_salesorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='partner_type',
            field=models.CharField(choices=[('supplier', 'Supplier')], default='supplier', max_length=20),
        ),
    ]
