# Generated by Django 6.0.4 on 2026-06-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_cost_price_remove_product_msrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'inventory_tag_groups',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('company_id', 'branch_id', 'slug')},
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['product', 'tag'], name='inventory_p_product_d01c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='producttag',
            index=models.Index(fields=['tag'], name='inventory_p_tag_id_5abf56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taggroup',
            unique_together={('company_id', 'branch_id', 'slug')},
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='inventory.taggroup'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='inventory_t_slug_5e9770_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['group', 'name'], name='inventory_t_group_i_e51d6d_idx'),
        ),
    ]
