# Generated by Django 6.0.4 on 2026-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_salesreturnline_quantity_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderline',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
