# Generated by Django 6.0.4 on 2026-05-21 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditfieldchange_alter_auditlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('STOCK_MOVEMENT', 'Stock Movement'), ('ORDER_CREATED', 'Order Created'), ('ORDER_COMPLETED', 'Order Completed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('TRANSFER_CONFIRMED', 'Transfer Confirmed'), ('PRICE_CHANGE', 'Price Change'), ('SYSTEM', 'System')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('target_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'branch_id', '-created_at'], name='inventory_a_company_778246_idx'), models.Index(fields=['target_user_id', 'is_read'], name='inventory_a_target__5f9255_idx'), models.Index(fields=['type', 'severity'], name='inventory_a_type_d86196_idx')],
            },
        ),
    ]
