# Generated by Django 6.0.4 on 2026-05-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_salesorderline_quantity_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnline',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='quantity_returned',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesreturnline',
            name='restock',
            field=models.BooleanField(default=True),
        ),
    ]
