# Generated by Django 6.0.4 on 2026-06-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchaseorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='image_url_thumb',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
