# Generated by Django 6.0.4 on 2026-06-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_taggroup_alter_tag_name_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(db_index=True)),
                ('branch_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('rating', models.PositiveSmallIntegerField(default=3, help_text='1-5 stars')),
                ('partner_type', models.CharField(choices=[('supplier', 'Supplier'), ('vendor', 'Vendor')], default='supplier', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers_partner',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company_id', 'branch_id'], name='suppliers_p_company_b33f3c_idx'), models.Index(fields=['code'], name='suppliers_p_code_8d2bb6_idx'), models.Index(fields=['partner_type'], name='suppliers_p_partner_850936_idx'), models.Index(fields=['status'], name='suppliers_p_status_1cd0db_idx')],
                'unique_together': {('company_id', 'branch_id', 'code')},
            },
        ),
    ]
