# Generated by Django 6.0.4 on 2026-06-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_supplier_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='source',
            field=models.CharField(choices=[('INVENTORY', 'Inventory'), ('SALES_POS', 'Sales POS'), ('SALES_AGENT', 'Sales Agent'), ('SALES_QUOTE', 'Sales Quote')], db_index=True, default='INVENTORY', max_length=20),
        ),
    ]
