# Generated by Django 6.0.4 on 2026-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salesorder_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='inventory_type',
            field=models.CharField(choices=[('FOR_SALE', 'For Sale (Inventory)'), ('OFFICE_INVENTORY', 'Office Inventory (Asset)')], default='FOR_SALE', help_text='Type of inventory: for resale or office assets', max_length=20),
        ),
    ]
