# Generated by Django 6.0.4 on 2026-06-27 13:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variantimage_image_url_thumb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('PAYMENT', 'Payment'), ('CREDIT_NOTE', 'Credit Note'), ('INVOICE_ADJUSTMENT', 'Invoice Adjustment'), ('CREDIT_APPLIED', 'Credit Applied')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reference_type', models.CharField(blank=True, help_text='e.g. supplier_bill, payment, customer_invoice', max_length=50)),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the referenced document', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_supplier_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['supplier'], name='inventory_s_supplie_0a3199_idx'), models.Index(fields=['transaction_type'], name='inventory_s_transac_99d801_idx')],
            },
        ),
    ]
