# Generated by Django 6.0.4 on 2026-05-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salesreturnline_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnline',
            name='restock',
            field=models.BooleanField(default=True, help_text='If True, quantity is added back to stock'),
        ),
    ]
