# Generated by Django 6.0.4 on 2026-06-28 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplier_balance_supplier_credit_supplierhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running net balance owed to this supplier', max_digits=15),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (surplus paid) with this supplier', max_digits=15),
        ),
    ]
