# Generated by Django 6.0.4 on 2026-06-10 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_employeeassetassignment_quantity'),
        ('inventory', '0007_purchaseorderline_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='current_occupancy',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='phone',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
