# Generated by Django 6.0.4 on 2026-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplier_balance_supplier_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierhistory',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('PURCHASE_REVERSAL', 'Purchase Reversal'), ('PAYMENT', 'Payment'), ('CREDIT_NOTE', 'Credit Note'), ('INVOICE_ADJUSTMENT', 'Invoice Adjustment'), ('CREDIT_APPLIED', 'Credit Applied')], max_length=50),
        ),
    ]
