# Generated by Django 6.0.4 on 2026-07-03 06:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_supplierhistory_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRefund',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('return_type', models.CharField(choices=[('INVOICE', 'Customer Invoice'), ('POS', 'POS Sale')], max_length=10)),
                ('document_id', models.UUIDField(help_text='UUID (_id) of the source CustomerInvoice or SalesOrder')),
                ('document_number', models.CharField(blank=True, help_text='Human-readable document number (invoice_number or order_number)', max_length=50)),
                ('return_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reason', models.TextField(blank=True)),
                ('refund_payment_id', models.UUIDField(blank=True, help_text='UUID of the refund payment created (if refunded to original method)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_refunds', to='inventory.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Warehouse receiving returned goods', on_delete=django.db.models.deletion.PROTECT, related_name='return_refunds', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'return_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRefundLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_line_id', models.UUIDField(help_text='UUID of the original document line')),
                ('is_manual_entry', models.BooleanField(default=False)),
                ('manual_variant_name', models.CharField(blank=True, max_length=200)),
                ('manual_variant_sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('restock', models.BooleanField(default=True, help_text='If True, quantity is added back to inventory')),
                ('return_to_supplier', models.BooleanField(default=False, help_text='If True, reverse the supplier bill/bill line for this item')),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('return_refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.returnrefund')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.productvariant')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_lines', to='inventory.supplier')),
            ],
            options={
                'db_table': 'return_refund_lines',
            },
        ),
        migrations.AddIndex(
            model_name='returnrefund',
            index=models.Index(fields=['company_id', 'branch_id'], name='return_refu_company_0ac050_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrefund',
            index=models.Index(fields=['return_type', 'document_id'], name='return_refu_return__dd79bd_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrefund',
            index=models.Index(fields=['status'], name='return_refu_status_119bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrefundline',
            index=models.Index(fields=['return_refund'], name='return_refu_return__5ae289_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrefundline',
            index=models.Index(fields=['source_line_id'], name='return_refu_source__77981c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrefundline',
            index=models.Index(fields=['variant'], name='return_refu_variant_78d6d2_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrefundline',
            index=models.Index(fields=['company_id', 'branch_id'], name='return_refu_company_ce1cb0_idx'),
        ),
    ]
