# Generated by Django 6.0.4 on 2026-05-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_customer_salesorder_salesorderline_salesreturn_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_entity__ff6b98_idx',
            old_name='audit_logs_entity__d4c2e5_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='inventory_a_created_e6162c_idx',
            old_name='audit_logs_created_43fcd6_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='inventory_audit_logs',
        ),
    ]
