# Generated by Django 6.0.4 on 2026-07-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_returnrefundline_disposition_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
