# Generated by Django 6.0.7 on 2026-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_fix_unit_cost_decimal_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('excel', 'Excel'), ('csv', 'CSV')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('excel', 'Excel'), ('csv', 'CSV')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('excel', 'Excel'), ('csv', 'CSV')], default='manual', max_length=20),
        ),
    ]
