# Generated by Django 6.0.4 on 2026-06-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compsetting', '0002_initial'),
        ('hr', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='categories', to='hr.asset'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='hr.asset'),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_requests', to='inventory.purchaseorder'),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationmonthrange',
            name='compensation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='month_range', to='hr.compensation'),
        ),
        migrations.AddField(
            model_name='compensationmonthrange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationmonthrange',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationmonthrange',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationselectedmonth',
            name='compensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_months', to='hr.compensation'),
        ),
        migrations.AddField(
            model_name='compensationselectedmonth',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationselectedmonth',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensationselectedmonth',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='compsetting.designation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='isfrom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assetpurchaserequest',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='hr.asset'),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='source_kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_assignments', to='hr.assetcategory'),
        ),
        migrations.AddField(
            model_name='employeeassetassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedefaultshift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedefaultshift',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedefaultshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_shifts', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeedefaultshift',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='exitchecklist',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_checklist_items', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='exitchecklist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_exit_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitchecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitchecklist',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitchecklist',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_records', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='exitrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitchecklist',
            name='exit_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='hr.exitrecord'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanmonthrange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanmonthrange',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanmonthrange',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='month_range', to='hr.employeeloan'),
        ),
        migrations.AddField(
            model_name='loanmonthrange',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanselectedmonth',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanselectedmonth',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanselectedmonth',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_months', to='hr.employeeloan'),
        ),
        migrations.AddField(
            model_name='loanselectedmonth',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollcompensation',
            name='compensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.compensation'),
        ),
        migrations.AddField(
            model_name='payrollcompensation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollcompensation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollcompensation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolldeductiondetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolldeductiondetail',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrolldeductiondetail',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_deductions', to='hr.employeeloan'),
        ),
        migrations.AddField(
            model_name='payrolldeductiondetail',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollleavededuction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollleavededuction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollleavededuction',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='hr.leaverequest'),
        ),
        migrations.AddField(
            model_name='payrollleavededuction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollloandeduction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollloandeduction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollloandeduction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_loan_deductions', to='hr.employeeloan'),
        ),
        migrations.AddField(
            model_name='payrollloandeduction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollloandeduction',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_loan_deductions', to='hr.payrollrecord'),
        ),
        migrations.AddField(
            model_name='payrollleavededuction',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_leave_deductions', to='hr.payrollrecord'),
        ),
        migrations.AddField(
            model_name='payrolldeductiondetail',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_details', to='hr.payrollrecord'),
        ),
        migrations.AddField(
            model_name='payrollcompensation',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_compensations', to='hr.payrollrecord'),
        ),
        migrations.AddField(
            model_name='policy',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacknowledgment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacknowledgment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacknowledgment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='policyacknowledgment',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='hr.policy'),
        ),
        migrations.AddField(
            model_name='policyacknowledgment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policycategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policycategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policycategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hr.policy'),
        ),
        migrations.AddField(
            model_name='policyversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentactivitylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentactivitylog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentactivitylog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentactivitylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='converted_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_candidates', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentactivitylog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='hr.recruitmentcandidate'),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='hr.recruitmentcandidate'),
        ),
        migrations.AddField(
            model_name='shiftchangehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_changes_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftchangehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_history', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='shiftdaterangeassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftdaterangeassignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftdaterangeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_range_assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='shiftdaterangeassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftoverride',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftoverride',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='shiftoverride',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftoverride',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='shiftdaterangeassignment',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_range_assignments', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='shiftchangehistory',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_shift_changes', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='shiftchangehistory',
            name='to_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_shift_changes', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='employeeshiftschedule',
            name='shift_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedules', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='employeedefaultshift',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_default_shifts', to='hr.shifttemplate'),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_with_default_shift', to='hr.shifttemplate'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company_id', 'is_deleted'], name='hr_asset_company_eedf01_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['branch_id'], name='hr_asset_branch__dba7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='hr_asset_serial__9be7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_assigned'], name='hr_asset_is_assi_68bdcb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['vendor'], name='hr_asset_vendor_244faa_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='hr_asset_categor_ae31bf_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['company_id', 'is_deleted'], name='hr_assetcat_company_c5548e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['branch_id'], name='hr_assetcat_branch__87b3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategory',
            index=models.Index(fields=['is_active'], name='hr_assetcat_is_acti_23e4d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together={('company_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='compensationselectedmonth',
            index=models.Index(fields=['compensation'], name='hr_compensa_compens_2c926f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compensationselectedmonth',
            unique_together={('compensation', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['employee'], name='hr_compensa_employe_b365c3_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['company_id', 'status'], name='hr_compensa_company_af6ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['frequency_type'], name='hr_compensa_frequen_51c5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpurchaserequest',
            index=models.Index(fields=['company_id', 'status'], name='hr_assetpur_company_367b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpurchaserequest',
            index=models.Index(fields=['asset', 'status'], name='hr_assetpur_asset_i_6c3403_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpurchaserequest',
            index=models.Index(fields=['company_id', 'branch_id'], name='hr_assetpur_company_edf857_idx'),
        ),
        migrations.AddIndex(
            model_name='assetpurchaserequest',
            index=models.Index(fields=['purchase_order'], name='hr_assetpur_purchas_4d5863_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassetassignment',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_9394b9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassetassignment',
            index=models.Index(fields=['asset', 'status'], name='hr_employee_asset_i_af1fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassetassignment',
            index=models.Index(fields=['company_id', 'status'], name='hr_employee_company_5957b0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeassetassignment',
            index=models.Index(fields=['source_kit'], name='hr_employee_source__df232a_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeassetassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('employee', 'asset'), name='unique_active_assignment'),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['employee', 'status'], name='hr_employee_employe_90799c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['company_id', 'status'], name='hr_employee_company_a95fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['frequency_type'], name='hr_employee_frequen_a7717f_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company_id', 'is_deleted'], name='hr_exit_rec_company_5dd130_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company_id', 'status'], name='hr_exit_rec_company_7b62ad_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company_id', 'reason'], name='hr_exit_rec_company_61174f_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['employee', 'status'], name='hr_exit_rec_employe_ac755c_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['exit_date'], name='hr_exit_rec_exit_da_c7e029_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['last_working_day'], name='hr_exit_rec_last_wo_5d95ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='exitrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'PENDING')), fields=('employee',), name='unique_active_exit_per_employee'),
        ),
        migrations.AddIndex(
            model_name='exitchecklist',
            index=models.Index(fields=['exit_record', 'status'], name='hr_exit_che_exit_re_ceaa26_idx'),
        ),
        migrations.AddIndex(
            model_name='exitchecklist',
            index=models.Index(fields=['exit_record', 'item_type'], name='hr_exit_che_exit_re_b0a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='exitchecklist',
            index=models.Index(fields=['assigned_to', 'status'], name='hr_exit_che_assigne_de5c80_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['company_id', 'status'], name='hr_leave_re_company_3163e6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'status'], name='hr_leave_re_employe_8e5342_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_leave_re_start_d_b9facf_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['applied_at'], name='hr_leave_re_applied_3dc16f_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['company_id', 'employee', 'status'], name='hr_leave_re_company_986e34_idx'),
        ),
        migrations.AddIndex(
            model_name='loanselectedmonth',
            index=models.Index(fields=['loan'], name='hr_loansele_loan_id_12e017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanselectedmonth',
            unique_together={('loan', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['company_id', 'month', 'year'], name='hr_payrollr_company_64b106_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['employee', 'is_cancelled'], name='hr_payrollr_employe_cbcb4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='payrollloandeduction',
            index=models.Index(fields=['payroll'], name='hr_payrolll_payroll_75fc01_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollloandeduction',
            index=models.Index(fields=['loan'], name='hr_payrolll_loan_id_76be0e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollleavededuction',
            index=models.Index(fields=['payroll'], name='hr_payrolll_payroll_12114e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollleavededuction',
            index=models.Index(fields=['leave_request'], name='hr_payrolll_leave_r_8a681e_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldeductiondetail',
            index=models.Index(fields=['payroll', 'deduction_type'], name='hr_payrolld_payroll_9568b2_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolldeductiondetail',
            index=models.Index(fields=['loan'], name='hr_payrolld_loan_id_e35469_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcompensation',
            index=models.Index(fields=['payroll', 'compensation'], name='hr_payrollc_payroll_b9afc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollcompensation',
            unique_together={('payroll', 'compensation')},
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company_id', 'status'], name='hr_policies_company_e527ff_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company_id', 'category'], name='hr_policies_company_771a79_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company_id', 'department'], name='hr_policies_company_fd0bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company_id', 'employee_type'], name='hr_policies_company_c5f023_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['code'], name='hr_policies_code_e2d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['effective_date'], name='hr_policies_effecti_b79e4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('company_id', 'code'), name='unique_company_policy_code'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['policy', 'employee'], name='hr_policy_a_policy__ee55f5_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['employee', 'acknowledged_at'], name='hr_policy_a_employe_e7ef8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgment',
            constraint=models.UniqueConstraint(fields=('policy', 'employee'), name='unique_policy_employee_acknowledgment'),
        ),
        migrations.AlterUniqueTogether(
            name='policycategory',
            unique_together={('company_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['policy', 'version'], name='hr_policy_v_policy__8f0e49_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company_id', 'is_deleted'], name='hr_recruitm_company_3db9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company_id', 'stage', 'status'], name='hr_recruitm_company_e179b4_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company_id', 'department'], name='hr_recruitm_company_f5fce4_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company_id', 'position'], name='hr_recruitm_company_e4044f_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['assigned_to', 'stage'], name='hr_recruitm_assigne_18bd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['apply_date'], name='hr_recruitm_apply_d_7fae4c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['source'], name='hr_recruitm_source_9c164c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['name', 'email'], name='hr_recruitm_name_6a9cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentactivitylog',
            index=models.Index(fields=['company_id', 'candidate'], name='hr_recruitm_company_47b85c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentactivitylog',
            index=models.Index(fields=['company_id', 'action', 'created_at'], name='hr_recruitm_company_74407a_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentactivitylog',
            index=models.Index(fields=['performed_by'], name='hr_recruitm_perform_00c89c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['candidate', 'round_number'], name='hr_intervie_candida_1f0e20_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['candidate', 'status'], name='hr_intervie_candida_006aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['interviewer'], name='hr_intervie_intervi_70ca16_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewround',
            index=models.Index(fields=['interview_date'], name='hr_intervie_intervi_c04b0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewround',
            unique_together={('candidate', 'round_number')},
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['company_id', 'is_deleted'], name='hr_shifttem_company_2f896e_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['branch_id'], name='hr_shifttem_branch__a6ee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['is_active'], name='hr_shifttem_is_acti_855c17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shifttemplate',
            unique_together={('company_id', 'name')},
        ),
        migrations.AddIndex(
            model_name='shiftoverride',
            index=models.Index(fields=['company_id', 'employee', 'date'], name='hr_shift_ov_company_8b43fa_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftoverride',
            index=models.Index(fields=['company_id', 'date'], name='hr_shift_ov_company_7d0681_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftoverride',
            index=models.Index(fields=['employee', 'date'], name='hr_shift_ov_employe_5e9a51_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftoverride',
            index=models.Index(fields=['shift_template'], name='hr_shift_ov_shift_t_d0b47a_idx'),
        ),
        migrations.AddConstraint(
            model_name='shiftoverride',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_shift_override'),
        ),
        migrations.AddIndex(
            model_name='shiftdaterangeassignment',
            index=models.Index(fields=['company_id', 'employee'], name='hr_shift_da_company_8a51e5_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftdaterangeassignment',
            index=models.Index(fields=['company_id', 'start_date', 'end_date'], name='hr_shift_da_company_74f747_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftdaterangeassignment',
            index=models.Index(fields=['employee', 'start_date', 'end_date'], name='hr_shift_da_employe_9ca8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftdaterangeassignment',
            index=models.Index(fields=['is_active'], name='hr_shift_da_is_acti_0c2c80_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftchangehistory',
            index=models.Index(fields=['company_id', 'employee'], name='hr_shift_ch_company_b95fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftchangehistory',
            index=models.Index(fields=['company_id', 'changed_at'], name='hr_shift_ch_company_9fa7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftchangehistory',
            index=models.Index(fields=['employee', 'changed_at'], name='hr_shift_ch_employe_ed21f2_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftchangehistory',
            index=models.Index(fields=['change_type'], name='hr_shift_ch_change__bc8473_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftchangehistory',
            index=models.Index(fields=['effective_from', 'effective_to'], name='hr_shift_ch_effecti_1cdad9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['company_id', 'date'], name='hr_employee_company_f58ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['employee', 'date'], name='hr_employee_employe_32b72b_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['company_id', 'employee', 'date'], name='hr_employee_company_a72550_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['shift_template'], name='hr_employee_shift_t_994da3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeshiftschedule',
            index=models.Index(fields=['source_type'], name='hr_employee_source__e0b050_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeshiftschedule',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date_schedule'),
        ),
        migrations.AddIndex(
            model_name='employeedefaultshift',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employee_employe_5bcf44_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company_id', 'is_deleted'], name='hr_employee_company_025d46_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['branch_id'], name='hr_employee_branch__ac35f2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='hr_employee_departm_1b8ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status'], name='hr_employee_employm_683961_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['cnic'], name='hr_employee_cnic_3e0a08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company_id', 'employee_id')},
        ),
    ]
