# Generated by Django 6.0.4 on 2026-05-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='hr_leave_ba_company_220512_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='hr_leave_ba_employe_98538b_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalance',
            name='hr_leave_ba_company_7f0784_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalancehistory',
            name='hr_leave_ba_company_474366_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalancehistory',
            name='hr_leave_ba_employe_fa8f0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavebalancehistory',
            name='hr_leave_ba_action_925c3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='yearendcarryforward',
            name='hr_year_end_company_0564b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='yearendcarryforward',
            name='hr_year_end_status_11fe32_idx',
        ),
        migrations.RemoveIndex(
            model_name='leaverequest',
            name='hr_leave_re_leave_y_bc25ca_idx',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('UNPAID', 'Unpaid Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('OTHER', 'Other')], default='CASUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='leave_request',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='leavebalancehistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='yearendcarryforward',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='yearendcarryforward',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='yearendcarryforward',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='yearendcarryforward',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type_name',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_year',
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
        migrations.DeleteModel(
            name='LeaveBalanceHistory',
        ),
        migrations.DeleteModel(
            name='YearEndCarryForward',
        ),
    ]
