# Generated by Django 6.0.4 on 2026-05-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttemplate',
            name='color',
        ),
    ]
