# Generated by Django 6.0.4 on 2026-06-12 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(db_index=True, max_length=255)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Offer', 'Offer Sent'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], db_index=True, default='Applied', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], db_index=True, default='Active', max_length=20)),
                ('apply_date', models.DateField(db_index=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('assigned_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('WEBSITE', 'Company Website'), ('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('REFERRAL', 'Employee Referral'), ('AGENCY', 'Recruitment Agency'), ('WALKIN', 'Walk-in'), ('OTHER', 'Other')], db_index=True, max_length=50, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('current_position', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notice_period_days', models.PositiveIntegerField(blank=True, null=True)),
                ('interview_round', models.PositiveSmallIntegerField(default=0)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('interviewers', models.TextField(blank=True, null=True)),
                ('offer_sent_date', models.DateField(blank=True, null=True)),
                ('offer_accepted_date', models.DateField(blank=True, null=True)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to='hr.employee')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_candidates', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_candidates', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recruitment_candidates', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recruitment_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruitment Candidate',
                'verbose_name_plural': 'Recruitment Candidates',
                'db_table': 'hr_recruitment_candidates',
                'ordering': ['-apply_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('CREATED', 'Candidate Created'), ('STAGE_CHANGED', 'Stage Changed'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('OFFER_SENT', 'Offer Sent'), ('OFFER_ACCEPTED', 'Offer Accepted'), ('OFFER_REJECTED', 'Offer Rejected'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('NOTE_ADDED', 'Note Added'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('DOCUMENT_ADDED', 'Document Added')], db_index=True, max_length=30)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_activity_logs', to='organization.company')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_activities', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='hr.recruitmentcandidate')),
            ],
            options={
                'verbose_name': 'Recruitment Activity Log',
                'verbose_name_plural': 'Recruitment Activity Logs',
                'db_table': 'hr_recruitment_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company', 'is_deleted'], name='hr_recruitm_company_3db9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company', 'stage', 'status'], name='hr_recruitm_company_e179b4_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company', 'department'], name='hr_recruitm_company_f5fce4_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['company', 'position'], name='hr_recruitm_company_e4044f_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['assigned_to', 'stage'], name='hr_recruitm_assigne_18bd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['apply_date'], name='hr_recruitm_apply_d_7fae4c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['source'], name='hr_recruitm_source_9c164c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcandidate',
            index=models.Index(fields=['name', 'email'], name='hr_recruitm_name_6a9cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentactivitylog',
            index=models.Index(fields=['company', 'candidate'], name='hr_recruitm_company_47b85c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentactivitylog',
            index=models.Index(fields=['company', 'action', 'created_at'], name='hr_recruitm_company_74407a_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentactivitylog',
            index=models.Index(fields=['performed_by'], name='hr_recruitm_perform_00c89c_idx'),
        ),
    ]
