# Generated by Django 6.0.4 on 2026-06-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0003_remove_companysettinghistory_compsetting_setting_859d54_idx_and_more'),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='compsetting.designation'),
        ),
    ]
