# Generated by Django 6.0.4 on 2026-06-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policy',
            name='hr_policies_effecti_b79e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='policy',
            new_name='hr_policies_company_58b067_idx',
            old_name='hr_policies_company_fd0bf4_idx',
        ),
        migrations.RemoveField(
            model_name='policyversion',
            name='effective_date',
        ),
        migrations.AlterField(
            model_name='policy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='organization.department'),
        ),
        migrations.RemoveField(
            model_name='policy',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='review_date',
        ),
    ]
