# Generated by Django 6.0.4 on 2026-06-12 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_recruitmentcandidate_recruitmentactivitylog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('round_title', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('TECHNICAL', 'Technical Interview'), ('HR', 'HR Interview'), ('MANAGERIAL', 'Managerial Interview'), ('CODING', 'Coding Test'), ('ASSIGNMENT', 'Assignment Review'), ('BEHAVIORAL', 'Behavioral Assessment'), ('GROUP', 'Group Discussion'), ('PRESENTATION', 'Presentation'), ('OTHER', 'Other')], default='TECHNICAL', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Rating out of 10', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='hr.recruitmentcandidate')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Interview Round',
                'verbose_name_plural': 'Interview Rounds',
                'db_table': 'hr_interview_rounds',
                'ordering': ['candidate', 'round_number'],
                'indexes': [models.Index(fields=['candidate', 'round_number'], name='hr_intervie_candida_1f0e20_idx'), models.Index(fields=['candidate', 'status'], name='hr_intervie_candida_006aa6_idx'), models.Index(fields=['interviewer'], name='hr_intervie_intervi_70ca16_idx'), models.Index(fields=['interview_date'], name='hr_intervie_intervi_c04b0d_idx')],
                'unique_together': {('candidate', 'round_number')},
            },
        ),
    ]
