# Generated by Django 6.0.4 on 2026-06-06 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='hr_payrollr_employe_3141cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='hr_payrollr_transac_e6def4_idx',
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='payrollrecord',
            index=models.Index(fields=['employee', 'is_cancelled'], name='hr_payrollr_employe_cbcb4d_idx'),
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payrollrecord',
            name='transaction_number',
        ),
    ]
