# Generated by Django 6.0.4 on 2026-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_payrolldeductiondetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('OTHER', 'Other')], default='CASUAL', max_length=20),
        ),
    ]
