# Generated by Django 6.0.4 on 2026-06-08 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_payrollrecord_hr_payrollr_employe_3141cf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Laptop, Monitor, Furniture', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='asset',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category'], name='hr_asset_categor_ae31bf_idx'),
        ),
    ]
