# Generated by Django 6.0.4 on 2026-06-12 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_interviewround'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('employee_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('exit_date', models.DateField(db_index=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('RESIGNATION', 'Resignation'), ('TERMINATION', 'Termination'), ('CONTRACT_END', 'Contract End'), ('RETIREMENT', 'Retirement'), ('OTHER', 'Other')], db_index=True, default='RESIGNATION', max_length=50)),
                ('notice_served', models.BooleanField(default=True)),
                ('clearance_hr', models.BooleanField(default=False, verbose_name='HR Clearance')),
                ('clearance_it', models.BooleanField(default=False, verbose_name='IT Clearance')),
                ('clearance_finance', models.BooleanField(default=False, verbose_name='Finance Clearance')),
                ('clearance_admin', models.BooleanField(default=False, verbose_name='Admin Clearance')),
                ('clearance_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('final_settlement', models.DecimalField(decimal_places=2, default=0, help_text='Final settlement amount in company currency', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Handover details, asset returns, etc.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_records', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_records', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exit_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_records', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exit Record',
                'verbose_name_plural': 'Exit Records',
                'db_table': 'hr_exit_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExitChecklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_type', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance'), ('ADMIN', 'Admin'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('WAIVED', 'Waived'), ('NOT_APPLICABLE', 'Not Applicable')], default='PENDING', max_length=20)),
                ('assigned_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_checklist_items', to='hr.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_checklists', to='organization.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_exit_checklists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exit_checklists', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exit_checklists', to=settings.AUTH_USER_MODEL)),
                ('exit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='hr.exitrecord')),
            ],
            options={
                'verbose_name': 'Exit Checklist',
                'verbose_name_plural': 'Exit Checklists',
                'db_table': 'hr_exit_checklists',
                'ordering': ['item_type', 'item_name'],
            },
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company', 'is_deleted'], name='hr_exit_rec_company_5dd130_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company', 'status'], name='hr_exit_rec_company_7b62ad_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company', 'clearance_status'], name='hr_exit_rec_company_f919f8_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company', 'reason'], name='hr_exit_rec_company_61174f_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['employee', 'status'], name='hr_exit_rec_employe_ac755c_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['department', 'status'], name='hr_exit_rec_departm_df133f_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['exit_date'], name='hr_exit_rec_exit_da_c7e029_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['last_working_day'], name='hr_exit_rec_last_wo_5d95ae_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company', 'clearance_status', 'status'], name='exit_clearance_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exitrecord',
            index=models.Index(fields=['company', 'department', 'reason'], name='exit_dept_reason_idx'),
        ),
        migrations.AddConstraint(
            model_name='exitrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'ACTIVE')), fields=('employee',), name='unique_active_exit_per_employee'),
        ),
        migrations.AddIndex(
            model_name='exitchecklist',
            index=models.Index(fields=['exit_record', 'status'], name='hr_exit_che_exit_re_ceaa26_idx'),
        ),
        migrations.AddIndex(
            model_name='exitchecklist',
            index=models.Index(fields=['exit_record', 'item_type'], name='hr_exit_che_exit_re_b0a58f_idx'),
        ),
        migrations.AddIndex(
            model_name='exitchecklist',
            index=models.Index(fields=['assigned_to', 'status'], name='hr_exit_che_assigne_de5c80_idx'),
        ),
    ]
