# Generated by Django 6.0.4 on 2026-06-15 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_policy_hr_policies_effecti_b79e4c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='advance_for_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Future month this advance is for (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='advance_for_year',
            field=models.PositiveIntegerField(blank=True, help_text='Future year this advance is for', null=True),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['advance_for_month', 'advance_for_year'], name='hr_employee_advance_8f9971_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeloan',
            constraint=models.UniqueConstraint(condition=models.Q(('advance_for_month__isnull', False)), fields=('employee', 'advance_for_month', 'advance_for_year'), name='unique_employee_advance_for_month'),
        ),
    ]
