# Generated by Django 6.0.4 on 2026-06-11 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_isfrom_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='applicable_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='applicable_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='frequency_type',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('SELECTED_MONTH', 'Selected Month'), ('MONTH_RANGE', 'Month Range')], default='MONTH_RANGE', max_length=20),
        ),
        migrations.AddField(
            model_name='compensation',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='compensation',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='applicable_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='applicable_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='frequency_type',
            field=models.CharField(choices=[('ONE_TIME', 'One Time'), ('SELECTED_MONTH', 'Selected Month'), ('MONTH_RANGE', 'Month Range')], default='MONTH_RANGE', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-12', null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['frequency_type'], name='hr_compensa_frequen_51c5e5_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['frequency_type'], name='hr_employee_frequen_a7717f_idx'),
        ),
    ]
