# Generated by Django 6.0.4 on 2026-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_asset_category_alter_asset_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassetassignment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units assigned'),
        ),
    ]
