# Generated by Django 6.0.4 on 2026-06-12 12:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_exitrecord_exitinterview_exitchecklist_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(help_text='Unique policy code (e.g., POL-001)', max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('category', models.CharField(choices=[('Employment', 'Employment'), ('Code of Conduct', 'Code of Conduct'), ('Leave & Attendance', 'Leave & Attendance'), ('Compensation & Benefits', 'Compensation & Benefits'), ('Health & Safety', 'Health & Safety'), ('IT & Data Security', 'IT & Data Security'), ('Remote Work', 'Remote Work'), ('Performance', 'Performance'), ('Disciplinary', 'Disciplinary'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('department', models.CharField(db_index=True, default='ALL', max_length=100)),
                ('employee_type', models.CharField(choices=[('ALL', 'All Employees'), ('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERN', 'Intern')], db_index=True, default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('REVOKED', 'Revoked')], db_index=True, default='DRAFT', max_length=20)),
                ('effective_date', models.DateField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('content', models.TextField()),
                ('document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('requires_acknowledgment', models.BooleanField(db_index=True, default=False)),
                ('acknowledgment_deadline', models.PositiveIntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_via', models.CharField(default='WEB', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgments', to='hr.employee')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='hr.policy')),
            ],
            options={
                'db_table': 'hr_policy_acknowledgments',
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sorting_order', models.IntegerField(default=0)),
                ('color_code', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_categories', to='organization.company')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_policy_categories',
                'ordering': ['sorting_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('change_summary', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_changes', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hr.policy')),
            ],
            options={
                'db_table': 'hr_policy_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'status'], name='hr_policies_company_e527ff_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'category'], name='hr_policies_company_771a79_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'department'], name='hr_policies_company_fd0bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['company', 'employee_type'], name='hr_policies_company_c5f023_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['code'], name='hr_policies_code_e2d0a0_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['effective_date'], name='hr_policies_effecti_b79e4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_policy_code'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['policy', 'employee'], name='hr_policy_a_policy__ee55f5_idx'),
        ),
        migrations.AddIndex(
            model_name='policyacknowledgment',
            index=models.Index(fields=['employee', 'acknowledged_at'], name='hr_policy_a_employe_e7ef8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgment',
            constraint=models.UniqueConstraint(fields=('policy', 'employee'), name='unique_policy_employee_acknowledgment'),
        ),
        migrations.AddIndex(
            model_name='policyversion',
            index=models.Index(fields=['policy', 'version'], name='hr_policy_v_policy__8f0e49_idx'),
        ),
    ]
