# Generated by Django 6.0.4 on 2026-06-11 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_compensation_applicable_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Compensation', 'verbose_name_plural': 'Compensations'},
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='applicable_month',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='applicable_year',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='applicable_month',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='applicable_year',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='monthly_deduction',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='start_year',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='total_months',
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='CompensationMonthRange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('end_year', models.PositiveSmallIntegerField()),
                ('compensation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='month_range', to='hr.compensation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compensation Month Range',
                'verbose_name_plural': 'Compensation Month Ranges',
            },
        ),
        migrations.CreateModel(
            name='LoanMonthRange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('end_year', models.PositiveSmallIntegerField()),
                ('deduction', models.DecimalField(decimal_places=2, help_text='Auto-calculated, not editable', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='month_range', to='hr.employeeloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Month Range',
                'verbose_name_plural': 'Loan Month Ranges',
            },
        ),
        migrations.CreateModel(
            name='CompensationSelectedMonth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('year', models.PositiveSmallIntegerField()),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_months', to='hr.compensation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compensation Selected Month',
                'verbose_name_plural': 'Compensation Selected Months',
                'ordering': ['year', 'month'],
                'indexes': [models.Index(fields=['compensation'], name='hr_compensa_compens_2c926f_idx')],
                'unique_together': {('compensation', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LoanSelectedMonth',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('month', models.PositiveSmallIntegerField(help_text='1-12')),
                ('year', models.PositiveSmallIntegerField()),
                ('deduction', models.DecimalField(decimal_places=2, help_text='Auto-calculated but editable', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_months', to='hr.employeeloan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Selected Month',
                'verbose_name_plural': 'Loan Selected Months',
                'ordering': ['year', 'month'],
                'indexes': [models.Index(fields=['loan'], name='hr_loansele_loan_id_12e017_idx')],
                'unique_together': {('loan', 'month', 'year')},
            },
        ),
    ]
