# Generated by Django 6.0.4 on 2026-06-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employeeloan_status_employeepromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_sub_type',
            field=models.CharField(choices=[('SHORT', 'Short Leave'), ('HALF', 'Half Leave'), ('FULL_DAY', 'Date Range')], default='FULL_DAY', help_text='Leave period type', max_length=20),
        ),
    ]
