# Generated by Django 6.0.4 on 2026-06-16 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_add_leave_sub_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloan',
            name='approval',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRM', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeloan',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeloan',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('RETURNED', 'Returned')], default='UNPAID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeeloan',
            index=models.Index(fields=['company_id', 'approval'], name='hr_employee_company_a57615_idx'),
        ),
    ]
