# Generated by Django 6.0.4 on 2026-06-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_compensation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='fuel_allowance',
        ),
    ]
