# Generated by Django 6.0.4 on 2026-06-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employeeloan_approval_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='policyacknowledgment',
            name='hr_policy_a_policy__ee55f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='policyacknowledgment',
            name='hr_policy_a_employe_e7ef8b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='policyacknowledgment',
            name='unique_policy_employee_acknowledgment',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='acknowledgment_deadline',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='requires_acknowledgment',
        ),
        migrations.DeleteModel(
            name='PolicyAcknowledgment',
        ),
    ]
