# Generated by Django 6.0.4 on 2026-06-12 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_compensation_fuel_allowance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='total_compensation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_leave_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='total_loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='PayrollCompensation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Compensation amount applied for this payroll month', max_digits=12)),
                ('compensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.compensation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_compensations', to='hr.payrollrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Compensation',
                'verbose_name_plural': 'Payroll Compensations',
                'indexes': [models.Index(fields=['payroll', 'compensation'], name='hr_payrollc_payroll_b9afc8_idx')],
                'unique_together': {('payroll', 'compensation')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLeaveDeduction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('working_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='hr.leaverequest')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_leave_deductions', to='hr.payrollrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Leave Deduction',
                'verbose_name_plural': 'Payroll Leave Deductions',
                'indexes': [models.Index(fields=['payroll'], name='hr_payrolll_payroll_12114e_idx'), models.Index(fields=['leave_request'], name='hr_payrolll_leave_r_8a681e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollLoanDeduction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_loan_deductions', to='hr.employeeloan')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_loan_deductions', to='hr.payrollrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payroll Loan Deduction',
                'verbose_name_plural': 'Payroll Loan Deductions',
                'indexes': [models.Index(fields=['payroll'], name='hr_payrolll_payroll_75fc01_idx'), models.Index(fields=['loan'], name='hr_payrolll_loan_id_76be0e_idx')],
            },
        ),
    ]
