# Generated by Django 6.0.4 on 2026-06-12 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_payrollrecord_total_compensation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='compensation',
            name='hr_compensa_employe_33dd61_idx',
        ),
        migrations.RemoveIndex(
            model_name='compensation',
            name='hr_compensa_company_ace1e4_idx',
        ),
        migrations.RemoveField(
            model_name='employeeloan',
            name='end_date',
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['employee'], name='hr_compensa_employe_b365c3_idx'),
        ),
        migrations.AddIndex(
            model_name='compensation',
            index=models.Index(fields=['company_id', 'status'], name='hr_compensa_company_af6ef5_idx'),
        ),
        migrations.RemoveField(
            model_name='compensation',
            name='is_active',
        ),
    ]
