# Generated by Django 6.0.4 on 2026-06-13 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_remove_compensation_hr_compensa_employe_33dd61_idx_and_more'),
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('under_date', models.DateField(help_text='Date by which the asset is needed')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PURCHASE_ORDER_CREATED', 'Purchase Order Created'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='hr.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_requests', to='hr.employee')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_requests', to='inventory.purchaseorder')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Purchase Request',
                'verbose_name_plural': 'Asset Purchase Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_id', 'status'], name='hr_assetpur_company_367b6b_idx'), models.Index(fields=['asset', 'status'], name='hr_assetpur_asset_i_6c3403_idx'), models.Index(fields=['company_id', 'branch_id'], name='hr_assetpur_company_edf857_idx'), models.Index(fields=['purchase_order'], name='hr_assetpur_purchas_4d5863_idx')],
            },
        ),
    ]
