# Generated by Django 6.0.4 on 2026-06-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_assetpurchaserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='converted_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_candidates', to='hr.employee'),
        ),
    ]
