# Generated by Django 6.0.4 on 2026-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_recruitmentcandidate_converted_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitrecord',
            name='final_settlement_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
