# Generated by Django 6.0.4 on 2026-07-01 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_employee_profile_picture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfilePic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file_url', models.CharField(max_length=500)),
                ('file_url_thumb', models.CharField(blank=True, max_length=500, null=True)),
                ('file_url_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary/display picture')),
                ('is_face_validated', models.BooleanField(default=True, help_text='Passed face detection validation')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_pictures', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile Picture',
                'verbose_name_plural': 'Employee Profile Pictures',
                'ordering': ['-is_primary', 'sort_order', 'created_at'],
                'indexes': [models.Index(fields=['employee', 'is_primary'], name='hr_employee_employe_81a7d6_idx'), models.Index(fields=['employee', 'is_deleted'], name='hr_employee_employe_0a0ba6_idx')],
            },
        ),
    ]
