# Generated by Django 6.0.4 on 2026-06-10 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, max_length=10)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('record_id', models.UUIDField(db_index=True)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
