# Generated by Django 6.0.4 on 2026-05-08 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('leave_year_type', models.CharField(choices=[('CALENDAR', 'Calendar'), ('FISCAL', 'Fiscal')], default='CALENDAR', max_length=20)),
                ('fiscal_year_start', models.PositiveSmallIntegerField(default=1)),
                ('public_holidays', models.JSONField(default=list)),
                ('working_days', models.JSONField(default=list)),
                ('weekends', models.JSONField(default=list)),
                ('is_setup_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.company')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
