# Generated by Django 6.0.4 on 2026-05-08 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettingHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Setting History',
                'verbose_name_plural': 'Setting Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('default_days_per_year', models.PositiveIntegerField(default=0)),
                ('max_carry_forward_days', models.PositiveIntegerField(default=0)),
                ('min_days_per_request', models.PositiveIntegerField(default=1)),
                ('max_days_per_request', models.PositiveIntegerField(default=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_document', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_after_months', models.PositiveIntegerField(default=0, help_text='Months after joining when this leave becomes available')),
                ('gender_specific', models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male Only'), ('FEMALE', 'Female Only')], default='ALL', max_length=10)),
                ('color_code', models.CharField(default='#4A90E2', max_length=7)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_recurring_yearly', models.BooleanField(default=False)),
                ('is_half_day', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National'), ('RELIGIOUS', 'Religious'), ('COMPANY', 'Company Specific'), ('REGIONAL', 'Regional')], default='NATIONAL', max_length=50)),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_working', models.BooleanField(default=True)),
                ('start_time', models.TimeField(default='09:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('is_half_day', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Working Day',
                'verbose_name_plural': 'Working Days',
                'ordering': ['day'],
            },
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='public_holidays',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='weekends',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='working_days',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='allow_carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='default_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='default_start_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='leave_during_probation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='max_carry_forward_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='working_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
        migrations.AddIndex(
            model_name='companysettings',
            index=models.Index(fields=['company', 'is_deleted'], name='compsetting_company_e0898a_idx'),
        ),
        migrations.AddIndex(
            model_name='companysettings',
            index=models.Index(fields=['branch'], name='compsetting_branch__8e4a27_idx'),
        ),
        migrations.AddIndex(
            model_name='companysettings',
            index=models.Index(fields=['is_setup_completed'], name='compsetting_is_setu_3cd72c_idx'),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_history', to='organization.company'),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_types', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.company'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leave_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leave_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_holidays', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='organization.company'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workingday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_days', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='organization.company'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_working_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workingday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workingday',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_working_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companysettinghistory',
            index=models.Index(fields=['settings', '-created_at'], name='compsetting_setting_859d54_idx'),
        ),
        migrations.AddIndex(
            model_name='companysettinghistory',
            index=models.Index(fields=['company', 'field_name'], name='compsetting_company_aed28a_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['settings', 'is_active'], name='compsetting_setting_6b9f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='leavetype',
            index=models.Index(fields=['company', 'is_deleted'], name='compsetting_company_b0c1be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('settings', 'code')},
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['settings', 'date'], name='compsetting_setting_6e48ff_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['company', 'date'], name='compsetting_company_c55401_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['is_deleted', 'date'], name='compsetting_is_dele_8e6267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('settings', 'date', 'name')},
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['settings', 'is_working'], name='compsetting_setting_fa0cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['company', 'is_deleted'], name='compsetting_company_9c3263_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together={('settings', 'day')},
        ),
    ]
