# Generated by Django 6.0.4 on 2026-05-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0001_initial'),
        ('hr', '0002_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='leavetype',
            name='compsetting_setting_6b9f1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='leavetype',
            name='compsetting_company_b0c1be_idx',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='leave_during_probation',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
