# Generated by Django 6.0.4 on 2026-06-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compsetting', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettinghistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_history', to='organization.company'),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organization.company'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_company_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysettinghistory',
            name='company_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='designation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='organization.company'),
        ),
        migrations.AddField(
            model_name='designation',
            name='company_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='designation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_designations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='organization.department'),
        ),
        migrations.AddField(
            model_name='designation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_designations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_holidays', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='organization.company'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='company_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_holidays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workingday',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='working_days', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='organization.company'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='company_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='compsetting.companysettings'),
        ),
        migrations.AddField(
            model_name='workingday',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_working_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workingday',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workingday',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_working_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companysettings',
            index=models.Index(fields=['company', 'is_deleted'], name='compsetting_company_e0898a_idx'),
        ),
        migrations.AddIndex(
            model_name='companysettings',
            index=models.Index(fields=['branch'], name='compsetting_branch__8e4a27_idx'),
        ),
        migrations.AddIndex(
            model_name='companysettinghistory',
            index=models.Index(fields=['company_settings', '-created_at'], name='compsetting_company_20f0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='companysettinghistory',
            index=models.Index(fields=['company', 'field_name'], name='compsetting_company_aed28a_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['company', 'is_deleted'], name='compsetting_company_64f7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['branch'], name='compsetting_branch__f6d35c_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['department'], name='compsetting_departm_159b50_idx'),
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['is_active'], name='compsetting_is_acti_e08587_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['company_settings', 'date'], name='compsetting_company_691a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['company', 'date'], name='compsetting_company_c55401_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['is_deleted', 'date'], name='compsetting_is_dele_8e6267_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('company_settings', 'date', 'name')},
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['company_settings', 'is_working'], name='compsetting_company_cdf0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['company', 'is_deleted'], name='compsetting_company_9c3263_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together={('company_settings', 'day')},
        ),
    ]
