# Generated by Django 6.0.4 on 2026-06-11 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0002_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companysettinghistory',
            name='compsetting_setting_859d54_idx',
        ),
        migrations.RemoveIndex(
            model_name='publicholiday',
            name='compsetting_setting_6e48ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='workingday',
            name='compsetting_setting_fa0cf6_idx',
        ),
        migrations.RenameField(
            model_name='companysettinghistory',
            old_name='settings',
            new_name='company_settings',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='settings',
            new_name='company_settings',
        ),
        migrations.RenameField(
            model_name='publicholiday',
            old_name='settings',
            new_name='company_settings',
        ),
        migrations.RenameField(
            model_name='workingday',
            old_name='settings',
            new_name='company_settings',
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('company_settings', 'date', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workingday',
            unique_together={('company_settings', 'day')},
        ),
        migrations.AddIndex(
            model_name='companysettinghistory',
            index=models.Index(fields=['company_settings', '-created_at'], name='compsetting_company_20f0f7_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['company_settings', 'date'], name='compsetting_company_691a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='workingday',
            index=models.Index(fields=['company_settings', 'is_working'], name='compsetting_company_cdf0f9_idx'),
        ),
    ]
