# Generated by Django 6.0.4 on 2026-06-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
