# Generated by Django 6.0.4 on 2026-06-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companysettings',
            name='compsetting_is_setu_3cd72c_idx',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='is_setup_completed',
        ),
    ]
