# Generated by Django 6.0.4 on 2026-06-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0003_remove_companysettings_compsetting_is_setu_3cd72c_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['name'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.RemoveIndex(
            model_name='designation',
            name='compsetting_pay_gra_6bee38_idx',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='pay_grade',
        ),
    ]
