# Generated by Django 6.0.4 on 2026-05-08 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0003_designation'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['pay_grade', 'name'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.RemoveIndex(
            model_name='designation',
            name='compsetting_level_38ae3e_idx',
        ),
        migrations.AddIndex(
            model_name='designation',
            index=models.Index(fields=['pay_grade'], name='compsetting_pay_gra_6bee38_idx'),
        ),
        migrations.RemoveField(
            model_name='designation',
            name='level',
        ),
    ]
