# Generated by Django 6.0.4 on 2026-06-19 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0003_companysettings_logo'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('quote', 'Quote'), ('invoice', 'Invoice')], max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_conditions', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_conditions', to='organization.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_terms_conditions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_terms_conditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terms & Condition',
                'verbose_name_plural': 'Terms & Conditions',
                'indexes': [models.Index(fields=['company', 'type'], name='compsetting_company_15de6c_idx'), models.Index(fields=['company', 'is_deleted'], name='compsetting_company_242ea2_idx'), models.Index(fields=['branch'], name='compsetting_branch__1d11a9_idx')],
                'unique_together': {('company', 'type')},
            },
        ),
    ]
