# Generated by Django 6.0.4 on 2026-06-11 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0003_remove_companysettinghistory_compsetting_setting_859d54_idx_and_more'),
        ('organization', '0003_user_isfrom_employee'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='designation',
            new_name='compsetting_departm_159b50_idx',
            old_name='compsetting_departm_390207_idx',
        ),
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='organization.department'),
        ),
    ]
