# Generated by Django 6.0.4 on 2026-05-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0004_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='default_days_per_year',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='gender_specific',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='applicable_to',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_advance_notice_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='status',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
