# Generated by Django 6.0.4 on 2026-06-11 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0005_migrate_department_to_fk'),
        ('organization', '0003_user_isfrom_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='organization.department'),
        ),
    ]
