# Generated by Django 6.0.4 on 2026-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compsetting', '0005_remove_leavetype_default_days_per_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='applicable_to',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='carry_forward_allowed',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='max_days_per_year',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='min_advance_notice_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='status',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='default_days_per_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='gender_specific',
            field=models.CharField(choices=[('ALL', 'All'), ('MALE', 'Male Only'), ('FEMALE', 'Female Only')], default='ALL', max_length=10),
        ),
    ]
