# Generated by Django 6.0.4 on 2026-06-02 11:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('expense_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('SALARIES', 'Salaries'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('TRAVEL', 'Travel'), ('MARKETING', 'Marketing'), ('SOFTWARE', 'Software'), ('MAINTENANCE', 'Maintenance'), ('INSURANCE', 'Insurance'), ('TAXES', 'Taxes'), ('OTHER', 'Other')], max_length=50)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_expenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['company_id', 'branch_id'], name='finance_exp_company_f15bdc_idx'), models.Index(fields=['category'], name='finance_exp_categor_77b0c7_idx'), models.Index(fields=['expense_date'], name='finance_exp_expense_01b759_idx')],
            },
        ),
    ]
