# Generated by Django 6.0.4 on 2026-06-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
