# Generated by Django 6.0.4 on 2026-06-04 10:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_customerinvoice_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='book_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal ledger balance (all recorded transactions)', max_digits=15),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cleared_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual bank statement balance (reconciled transactions only)', max_digits=15),
        ),
    ]
