# Generated by Django 6.0.4 on 2026-06-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('RENT', 'Rent'), ('UTILITIES', 'Utilities'), ('SALARIES', 'Salaries'), ('STAFF_LOAN', 'Staff Loan'), ('EXIT_SETTLEMENT', 'Exit Settlement'), ('OFFICE_SUPPLIES', 'Office Supplies'), ('TRAVEL', 'Travel'), ('MARKETING', 'Marketing'), ('SOFTWARE', 'Software'), ('MAINTENANCE', 'Maintenance'), ('INSURANCE', 'Insurance'), ('TAXES', 'Taxes'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
