# Generated by Django 6.0.4 on 2026-06-27 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_category'),
        ('inventory', '0005_variantimage_image_url_thumb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoiceline',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='manual_variant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='manual_variant_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.productvariant'),
        ),
        migrations.AddIndex(
            model_name='customerinvoiceline',
            index=models.Index(fields=['vendor'], name='finance_cus_vendor__169ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoiceline',
            index=models.Index(fields=['is_manual_entry'], name='finance_cus_is_manu_186830_idx'),
        ),
    ]
