# Generated by Django 6.0.4 on 2026-06-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_customerinvoice_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='source',
            field=models.CharField(choices=[('FINANCE', 'Finance'), ('SALES_POS', 'Sales POS'), ('SALES_AGENT', 'Sales Agent'), ('SALES_QUOTE', 'Sales Quote')], db_index=True, default='FINANCE', max_length=20),
        ),
    ]
