# Generated by Django 6.0.4 on 2026-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_customerinvoiceline_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoice',
            name='overall_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='overall_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
