# Generated by Django 6.0.4 on 2026-06-06 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0007_customerinvoice_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_supplie_269573_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_custome_4addc0_idx',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='supplierbill',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('WALLET', 'Digital Wallet'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['content_type', 'object_id'], name='finance_pay_content_b36e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='finance_pay_status_632995_idx'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_invoice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='supplier_bill',
        ),
    ]
