# Generated by Django 6.0.4 on 2026-06-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_customerinvoiceline_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoiceline',
            name='supplier_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='finance.supplierbill'),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='customer_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_bills', to='finance.customerinvoice'),
        ),
    ]
