# Generated by Django 6.0.4 on 2026-06-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_payment_finance_pay_supplie_269573_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierbill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
