# Generated by Django 6.0.4 on 2026-06-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_customerinvoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.supplierbill'),
        ),
    ]
