# Generated by Django 6.0.4 on 2026-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_customerinvoiceline_supplier_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinvoiceline',
            name='original_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Pre-edit quantity for reduction conflict resolution', null=True),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='resolved',
            field=models.BooleanField(default=False, help_text='Whether the reduction conflict on this line has been resolved'),
        ),
    ]
