# Generated by Django 6.0.4 on 2026-06-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_expense_supplier_bill'),
        ('inventory', '0007_purchaseorderline_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='inventory.supplier'),
        ),
    ]
