# Generated by Django 6.0.4 on 2026-06-30 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_customerinvoiceline_original_quantity_and_more'),
        ('inventory', '0008_alter_supplierhistory_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineProductLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='finance.customerinvoiceline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_links', to='inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_links', to='inventory.productvariant')),
            ],
            options={
                'db_table': 'finance_invoice_line_product_links',
                'indexes': [models.Index(fields=['invoice_line'], name='finance_inv_invoice_c12c13_idx'), models.Index(fields=['variant'], name='finance_inv_variant_5d5875_idx')],
                'unique_together': {('invoice_line', 'variant')},
            },
        ),
    ]
