# Generated by Django 6.0.4 on 2026-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_customerinvoiceline_add_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('CREDIT', 'Supplier Credit'), ('WALLET', 'Digital Wallet'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
