/**
 * Schemas for every CRUD submodule aligned with BOS v1.0 Complete Blueprint.
 * Keys = localStorage keys from seeder.
 */
export const schemas = {
  // ─── INVENTORY ────────────────────────────────────────────────────────────

  products: {
    title: "Product Management",
    subtitle: "Manage products, SKUs, brands and stock levels",
    storeKey: "products",
    idPrefix: "p",
    statusField: "is_active",
    fields: [
      { key: "sku",               label: "SKU",                 type: "text",   required: true },
      { key: "name",              label: "Name",                type: "text",   required: true },
      { key: "description",       label: "Description",         type: "textarea" },
      { key: "category_id",       label: "Category",            type: "text",   required: true },
      { key: "brand",             label: "Brand",               type: "text" },
      { key: "unit_of_measure",   label: "Unit of Measure",     type: "select", options: ["PCS", "KG", "LTR", "MTR", "BOX", "SET"], required: true },
      { key: "product_type",      label: "Product Type",        type: "select", options: ["PRODUCT", "SERVICE", "ASSET", "CONSUMABLE"], required: true },
      { key: "cost_price",        label: "Cost Price",          type: "number", required: true },
      { key: "selling_price",     label: "Selling Price",       type: "number", required: true },
      { key: "min_selling_price", label: "Min Selling Price",   type: "number" },
      { key: "tax_rate_id",       label: "Tax Rate",            type: "text" },
      { key: "barcode",           label: "Barcode",             type: "text" },
      { key: "barcode_type",      label: "Barcode Type",        type: "select", options: ["EAN13", "QR", "CODE128", "CUSTOM"] },
      { key: "reorder_point",     label: "Reorder Point",       type: "number" },
      { key: "reorder_quantity",  label: "Reorder Quantity",    type: "number" },
      { key: "max_stock_level",   label: "Max Stock Level",     type: "number" },
      { key: "lead_time_days",    label: "Lead Time (Days)",    type: "number" },
      { key: "is_serialised",     label: "Serialised",          type: "select", options: ["true", "false"] },
      { key: "is_batch_tracked",  label: "Batch Tracked",       type: "select", options: ["true", "false"] },
      { key: "is_active",         label: "Status",              type: "select", options: ["true", "false"] },
    ],
    columns: ["sku", "name", "category_id", "brand", "selling_price", "reorder_point", "is_active"],
  },

  categories: {
    title: "Categories",
    storeKey: "categories",
    idPrefix: "cat",
    fields: [
      { key: "name",        label: "Name",        type: "text", required: true },
      { key: "parent_id",   label: "Parent",      type: "text" },
      { key: "description", label: "Description", type: "textarea" },
    ],
  },

  brands: {
    title: "Brands",
    storeKey: "brands",
    idPrefix: "br",
    fields: [
      { key: "name",    label: "Name",    type: "text", required: true },
      { key: "country", label: "Country", type: "text" },
    ],
  },

  stockMoves: {
    title: "Stock Management",
    subtitle: "Stock in/out, adjustments and transfers",
    storeKey: "stockMoves",
    idPrefix: "sm",
    statusField: "type",
    fields: [
      { key: "date",        label: "Date",          type: "date",   required: true },
      { key: "type",        label: "Type",          type: "select", options: ["STOCK_IN", "STOCK_OUT", "ADJUST", "TRANSFER"], required: true },
      { key: "product_id",  label: "Product",       type: "text",   required: true },
      { key: "qty",         label: "Quantity",      type: "number", required: true },
      { key: "warehouse_id",label: "Warehouse",     type: "text" },
      { key: "batch_number",label: "Batch Number",  type: "text" },
      { key: "serial_number",label: "Serial Number",type: "text" },
      { key: "reason",      label: "Reason Code",   type: "text" },
      { key: "note",        label: "Note",          type: "textarea" },
    ],
  },

  stockLevels: {
    title: "Stock Levels",
    subtitle: "Real-time stock per product per warehouse",
    storeKey: "stockLevels",
    idPrefix: "sl",
    fields: [
      { key: "product_id",         label: "Product",            type: "text",   required: true },
      { key: "warehouse_id",       label: "Warehouse",          type: "text",   required: true },
      { key: "location_id",        label: "Location (Bin)",     type: "text" },
      { key: "quantity_on_hand",   label: "Qty On Hand",        type: "number" },
      { key: "quantity_reserved",  label: "Qty Reserved",       type: "number" },
      { key: "quantity_on_order",  label: "Qty On Order",       type: "number" },
      { key: "batch_number",       label: "Batch Number",       type: "text" },
      { key: "serial_number",      label: "Serial Number",      type: "text" },
      { key: "expiry_date",        label: "Expiry Date",        type: "date" },
      { key: "last_counted_at",    label: "Last Counted",       type: "date" },
    ],
    columns: ["product_id", "warehouse_id", "quantity_on_hand", "quantity_reserved", "quantity_on_order", "expiry_date"],
  },

  warehouses: {
    title: "Warehouse Management",
    storeKey: "warehouses",
    idPrefix: "wh",
    fields: [
      { key: "name",       label: "Name",         type: "text",   required: true },
      { key: "code",       label: "Code",         type: "text",   required: true },
      { key: "address",    label: "Address",      type: "textarea" },
      { key: "city",       label: "City",         type: "text" },
      { key: "manager_id", label: "Manager",      type: "text" },
      { key: "phone",      label: "Phone",        type: "text" },
      { key: "capacity",   label: "Capacity",     type: "number" },
      { key: "is_active",  label: "Status",       type: "select", options: ["true", "false"] },
    ],
  },

  purchaseOrders: {
    title: "Purchase Orders",
    storeKey: "purchaseOrders",
    idPrefix: "po",
    statusField: "status",
    fields: [
      { key: "po_number",                label: "PO Number",            type: "text",   required: true },
      { key: "supplier_id",              label: "Supplier",             type: "text",   required: true },
      { key: "order_date",               label: "Order Date",           type: "date",   required: true },
      { key: "expected_delivery_date",   label: "Expected Delivery",    type: "date" },
      { key: "delivery_date",            label: "Actual Delivery",      type: "date" },
      { key: "warehouse_id",             label: "Destination Warehouse",type: "text",   required: true },
      { key: "subtotal",                 label: "Subtotal",             type: "number" },
      { key: "tax_amount",               label: "Tax Amount",           type: "number" },
      { key: "shipping_cost",            label: "Shipping Cost",        type: "number" },
      { key: "discount_amount",          label: "Discount Amount",      type: "number" },
      { key: "total_amount",             label: "Total Amount",         type: "number" },
      { key: "status",                   label: "Status",               type: "select", options: ["DRAFT", "SENT", "CONFIRMED", "PARTIAL", "RECEIVED", "CANCELLED"] },
      { key: "payment_status",           label: "Payment Status",       type: "select", options: ["UNPAID", "PARTIAL", "PAID"] },
      { key: "notes",                    label: "Notes",                type: "textarea" },
      { key: "terms",                    label: "Terms",                type: "textarea" },
    ],
    columns: ["po_number", "supplier_id", "order_date", "total_amount", "status", "payment_status"],
  },

  suppliers: {
    title: "Suppliers & Vendors",
    storeKey: "suppliers",
    idPrefix: "sup",
    statusField: "status",
    fields: [
      { key: "name",          label: "Name",              type: "text", required: true },
      { key: "code",          label: "Supplier Code",     type: "text" },
      { key: "contact",       label: "Contact Person",    type: "text" },
      { key: "email",         label: "Email",             type: "text" },
      { key: "phone",         label: "Phone",             type: "text" },
      { key: "address",       label: "Address",           type: "textarea" },
      { key: "city",          label: "City",              type: "text" },
      { key: "payment_terms", label: "Payment Terms",     type: "text" },
      { key: "credit_limit",  label: "Credit Limit",      type: "number" },
      { key: "balance",       label: "Balance",           type: "number" },
      { key: "rating",        label: "Rating",            type: "select", options: ["1", "2", "3", "4", "5"] },
      { key: "status",        label: "Status",            type: "select", options: ["Active", "Inactive"] },
    ],
    columns: ["name", "contact", "email", "phone", "balance", "status"],
  },

  salesOrders: {
    title: "Sales Orders",
    storeKey: "salesOrders",
    idPrefix: "so",
    statusField: "status",
    fields: [
      { key: "code",             label: "Order Code",       type: "text",   required: true },
      { key: "customer_id",      label: "Customer",         type: "text",   required: true },
      { key: "order_date",       label: "Order Date",       type: "date",   required: true },
      { key: "delivery_date",    label: "Delivery Date",    type: "date" },
      { key: "subtotal",         label: "Subtotal",         type: "number" },
      { key: "tax_amount",       label: "Tax Amount",       type: "number" },
      { key: "discount_amount",  label: "Discount Amount",  type: "number" },
      { key: "total_amount",     label: "Total Amount",     type: "number" },
      { key: "status",           label: "Status",           type: "select", options: ["DRAFT", "CONFIRMED", "PICKING", "DISPATCHED", "DELIVERED", "CANCELLED"] },
      { key: "payment_status",   label: "Payment Status",   type: "select", options: ["Pending", "Paid", "Partial", "Cancelled"] },
      { key: "notes",            label: "Notes",            type: "textarea" },
    ],
    columns: ["code", "customer_id", "order_date", "total_amount", "status", "payment_status"],
  },

  assetsInv: {
    title: "Assets Inventory",
    storeKey: "assetsInv",
    idPrefix: "ai",
    statusField: "status",
    fields: [
      { key: "name",          label: "Name",          type: "text",   required: true },
      { key: "tag",           label: "Asset Tag",      type: "text",   required: true },
      { key: "category",      label: "Category",       type: "text" },
      { key: "serial_number", label: "Serial Number",  type: "text" },
      { key: "purchase_date", label: "Purchase Date",  type: "date" },
      { key: "purchase_value",label: "Purchase Value", type: "number" },
      { key: "current_value", label: "Current Value",  type: "number" },
      { key: "assignedTo",    label: "Assigned To",    type: "text" },
      { key: "location",      label: "Location",       type: "text" },
      { key: "status",        label: "Status",         type: "select", options: ["Available", "Assigned", "Under Repair", "Retired"] },
    ],
    columns: ["tag", "name", "category", "assignedTo", "current_value", "status"],
  },

  transfers: {
    title: "Inventory Transfers",
    storeKey: "transfers",
    idPrefix: "tr",
    statusField: "status",
    fields: [
      { key: "code",         label: "Transfer Code",  type: "text", required: true },
      { key: "from",         label: "From Warehouse", type: "text", required: true },
      { key: "to",           label: "To Warehouse",   type: "text", required: true },
      { key: "date",         label: "Date",           type: "date", required: true },
      { key: "items",        label: "Items Count",    type: "number" },
      { key: "approved_by",  label: "Approved By",    type: "text" },
      { key: "status",       label: "Status",         type: "select", options: ["DRAFT", "Pending", "In Transit", "Completed", "Cancelled"] },
      { key: "notes",        label: "Notes",          type: "textarea" },
    ],
    columns: ["code", "from", "to", "date", "items", "status"],
  },

  barcodes: {
    title: "Barcode & QR",
    storeKey: "barcodes",
    idPrefix: "bc",
    fields: [
      { key: "product_id", label: "Product",    type: "text",   required: true },
      { key: "code",       label: "Code",       type: "text",   required: true },
      { key: "type",       label: "Type",       type: "select", options: ["EAN13", "QR", "CODE128", "CUSTOM"] },
      { key: "printed_at", label: "Printed At", type: "date" },
    ],
  },

  posReceipts: {
    title: "Selling / POS",
    subtitle: "POS billing, sales orders & receipts",
    storeKey: "posReceipts",
    idPrefix: "rcp",
    statusField: "payment",
    fields: [
      { key: "code",         label: "Receipt Code",    type: "text",   required: true },
      { key: "cashier",      label: "Cashier",         type: "text",   required: true },
      { key: "date",         label: "Date",            type: "date",   required: true },
      { key: "subtotal",     label: "Subtotal",        type: "number" },
      { key: "tax_amount",   label: "Tax Amount",      type: "number" },
      { key: "discount",     label: "Discount",        type: "number" },
      { key: "total",        label: "Total",           type: "number", required: true },
      { key: "items",        label: "Items Count",     type: "number" },
      { key: "payment",      label: "Payment Method",  type: "select", options: ["Cash", "Card", "Bank", "Mixed"] },
      { key: "customer_id",  label: "Customer",        type: "text" },
    ],
    columns: ["code", "cashier", "date", "total", "items", "payment"],
  },

  alerts: {
    title: "Alerts",
    storeKey: "alerts",
    idPrefix: "al",
    statusField: "severity",
    fields: [
      { key: "type",      label: "Type",     type: "select", options: ["LOW_STOCK", "OVERSTOCK", "EXPIRY", "PENDING_PO", "UNCONFIRMED_GRN"], required: true },
      { key: "message",   label: "Message",  type: "textarea" },
      { key: "severity",  label: "Severity", type: "select", options: ["Low", "Medium", "High", "Critical"] },
      { key: "module",    label: "Module",   type: "text" },
      { key: "date",      label: "Date",     type: "date" },
      { key: "resolved",  label: "Resolved", type: "select", options: ["false", "true"] },
    ],
  },

  auditLogs: {
    title: "Audit Logs",
    storeKey: "auditLogs",
    idPrefix: "log",
    fields: [
      { key: "user_id",    label: "User",       type: "text" },
      { key: "action",     label: "Action",     type: "text" },
      { key: "module",     label: "Module",     type: "text" },
      { key: "resource",   label: "Resource",   type: "text" },
      { key: "resource_id",label: "Record ID",  type: "text" },
      { key: "old_values", label: "Old Values", type: "textarea" },
      { key: "new_values", label: "New Values", type: "textarea" },
      { key: "ip_address", label: "IP Address", type: "text" },
      { key: "date",       label: "Date",       type: "text" },
    ],
    columns: ["user_id", "action", "module", "resource", "date"],
  },

  // ─── HR ───────────────────────────────────────────────────────────────────

  employees: {
    title: "Employee Management",
    storeKey: "employees",
    idPrefix: "emp",
    statusField: "employment_status",
    fields: [
      { key: "employee_id",              label: "Employee Id",          type: "text",   required: true },
      { key: "first_name",                 label: "First Name",             type: "text",   required: true },
      { key: "last_name",                  label: "Last Name",              type: "text", },
      { key: "father_name",                label: "Father Name",            type: "text", required: true },
      { key: "cnic",                       label: "CNIC",                   type: "text",   required: true },
      { key: "date_of_birth",              label: "Date of Birth",          type: "date",   required: true },
      { key: "gender",                     label: "Gender",                 type: "select", options: ["MALE", "FEMALE", "OTHER"], required: true },
      { key: "marital_status",             label: "Marital Status",         type: "select", options: ["SINGLE", "MARRIED", "DIVORCED", "WIDOWED"] },
      { key: "phone",                      label: "Phone",                  type: "text",   required: true },
      { key: "email",                      label: "Work Email",             type: "text" },
      { key: "personal_email",             label: "Personal Email",         type: "text" },
      { key: "address",                    label: "Address",                type: "textarea" },
      { key: "city",                       label: "City",                   type: "text" },
      { key: "emergency_contact_name",     label: "Emergency Contact",      type: "text" },
      { key: "emergency_contact_phone",    label: "Emergency Phone",        type: "text" },
      { key: "emergency_contact_relation", label: "Emergency Relation",     type: "text" },
      { key: "role",        label: "Role",       type: "select", options: ["COMPANY_ADMIN", "BRANCH_ADMIN", "STAFF"], required: true },
      { key: "department",   label: "Department", type: "select", options: ["HR", "INVENTORY", "FINANCE"], required: true },
      { key: "designation",   label: "Designation", type: "text" },
      { key: "employment_type",            label: "Employment Type",        type: "select", options: ["FULL_TIME", "PART_TIME", "CONTRACT", "INTERN"], required: true },
      { key: "employment_status",          label: "Status",                 type: "select", options: ["ACTIVE", "ON_LEAVE", "SUSPENDED", "TERMINATED", "RESIGNED"] },
      { key: "joining_date",               label: "Joining Date",           type: "date",   required: true },
      { key: "confirmation_date",          label: "Confirmation Date",      type: "date" },
      { key: "probation_days",             label: "Probation Days",         type: "number" },
      { key: "work_location",              label: "Work Location",          type: "select", options: ["OFFICE", "REMOTE", "HYBRID"] },
      { key: "reporting_manager_id",       label: "Reporting Manager",      type: "text" },
      { key: "bank_name",                  label: "Bank Name",              type: "text" },
      { key: "bank_account_number",        label: "Bank Account #",         type: "text" },
      { key: "bank_iban",                  label: "Bank IBAN",              type: "text" },
      { key: "salary",                     label: "Basic Salary",           type: "number" },
    ],
    columns: ["employee_id", "first_name", "last_name", "department", "designation", "employment_type", "employment_status"],
  },

  payroll: {
    title: "Payroll Runs",
    storeKey: "payroll",
    idPrefix: "pr",
    statusField: "status",
    fields: [
      { key: "run_code",                    label: "Run Code",                  type: "text",   required: true },
      { key: "period_month",                label: "Month",                     type: "number", required: true },
      { key: "period_year",                 label: "Year",                      type: "number", required: true },
      { key: "run_type",                    label: "Run Type",                  type: "select", options: ["MONTHLY", "SUPPLEMENTARY", "FINAL"] },
      { key: "total_gross",                 label: "Total Gross",               type: "number" },
      { key: "total_deductions",            label: "Total Deductions",          type: "number" },
      { key: "total_net",                   label: "Total Net",                 type: "number" },
      { key: "total_employer_contributions",label: "Employer Contributions",    type: "number" },
      { key: "approved_by_id",              label: "Approved By",               type: "text" },
      { key: "paid_at",                     label: "Paid At",                   type: "date" },
      { key: "status",                      label: "Status",                    type: "select", options: ["DRAFT", "PROCESSING", "APPROVED", "PAID", "LOCKED"] },
      { key: "notes",                       label: "Notes",                     type: "textarea" },
    ],
    columns: ["run_code", "period_month", "period_year", "total_gross", "total_net", "status"],
  },

  payrollSlips: {
    title: "Payroll Slips",
    storeKey: "payrollSlips",
    idPrefix: "psl",
    statusField: "payment_status",
    fields: [
      { key: "payroll_run_id",       label: "Payroll Run",           type: "text",   required: true },
      { key: "employee_id",          label: "Employee",              type: "text",   required: true },
      { key: "basic_salary",         label: "Basic Salary",          type: "number", required: true },
      { key: "house_rent_allowance", label: "HRA",                   type: "number" },
      { key: "medical_allowance",    label: "Medical Allowance",     type: "number" },
      { key: "transport_allowance",  label: "Transport Allowance",   type: "number" },
      { key: "overtime_hours",       label: "Overtime Hours",        type: "number" },
      { key: "overtime_amount",      label: "Overtime Amount",       type: "number" },
      { key: "bonus",                label: "Bonus",                 type: "number" },
      { key: "gross_salary",         label: "Gross Salary",          type: "number" },
      { key: "income_tax",           label: "Income Tax",            type: "number" },
      { key: "eobi_employee",        label: "EOBI (Employee)",       type: "number" },
      { key: "eobi_employer",        label: "EOBI (Employer)",       type: "number" },
      { key: "pessi_employee",       label: "PESSI (Employee)",      type: "number" },
      { key: "loan_deduction",       label: "Loan Deduction",        type: "number" },
      { key: "advance_deduction",    label: "Advance Deduction",     type: "number" },
      { key: "late_deduction",       label: "Late Deduction",        type: "number" },
      { key: "absent_deduction",     label: "Absent Deduction",      type: "number" },
      { key: "total_deductions",     label: "Total Deductions",      type: "number" },
      { key: "net_salary",           label: "Net Salary",            type: "number" },
      { key: "payment_method",       label: "Payment Method",        type: "select", options: ["BANK", "CASH", "CHEQUE"] },
      { key: "payment_status",       label: "Payment Status",        type: "select", options: ["PENDING", "PAID", "FAILED"] },
      { key: "paid_at",              label: "Paid At",               type: "date" },
    ],
    columns: ["employee_id", "payroll_run_id", "gross_salary", "total_deductions", "net_salary", "payment_status"],
  },

  attendance: {
    title: "Time & Attendance",
    storeKey: "attendance",
    idPrefix: "at",
    statusField: "status",
    fields: [
      { key: "attendance_date",    label: "Date",              type: "date",   required: true },
      { key: "employee_id",        label: "Employee",          type: "text",   required: true },
      { key: "check_in_time",      label: "Check In",          type: "text" },
      { key: "check_out_time",     label: "Check Out",         type: "text" },
      { key: "expected_in",        label: "Expected In",       type: "text" },
      { key: "expected_out",       label: "Expected Out",      type: "text" },
      { key: "late_minutes",       label: "Late (mins)",       type: "number" },
      { key: "overtime_minutes",   label: "Overtime (mins)",   type: "number" },
      { key: "work_hours",         label: "Work Hours",        type: "number" },
      { key: "source",             label: "Source",            type: "select", options: ["MANUAL", "BIOMETRIC", "APP", "IMPORT"] },
      { key: "status",             label: "Status",            type: "select", options: ["PRESENT", "ABSENT", "LATE", "HALF_DAY", "ON_LEAVE", "HOLIDAY", "OFF"] },
      { key: "remarks",            label: "Remarks",           type: "textarea" },
    ],
    columns: ["attendance_date", "employee_id", "check_in_time", "check_out_time", "work_hours", "status"],
  },

  leaves: {
    title: "Leave Management",
    storeKey: "leaves",
    idPrefix: "lv",
    statusField: "status",
    fields: [
      { key: "employee_id",      label: "Employee",         type: "text",   required: true },
      { key: "leave_type_id",    label: "Leave Type",       type: "text",   required: true },
      { key: "start_date",       label: "Start Date",       type: "date",   required: true },
      { key: "end_date",         label: "End Date",         type: "date",   required: true },
      { key: "total_days",       label: "Total Days",       type: "number" },
      { key: "reason",           label: "Reason",           type: "textarea", required: true },
      { key: "approved_by_id",   label: "Approved By",      type: "text" },
      { key: "rejection_reason", label: "Rejection Reason", type: "textarea" },
      { key: "status",           label: "Status",           type: "select", options: ["PENDING", "APPROVED", "REJECTED", "CANCELLED"] },
    ],
    columns: ["employee_id", "leave_type_id", "start_date", "end_date", "total_days", "status"],
  },

  shifts: {
    title: "Shift Management",
    storeKey: "shifts",
    idPrefix: "sh",
    fields: [
      { key: "name",      label: "Shift Name",    type: "text", required: true },
      { key: "start",     label: "Start Time",    type: "text", required: true },
      { key: "end",       label: "End Time",      type: "text", required: true },
      { key: "employees", label: "Employees",     type: "number" },
      { key: "is_active", label: "Status",        type: "select", options: ["true", "false"] },
    ],
  },

  empAssets: {
    title: "Employee Assets",
    storeKey: "empAssets",
    idPrefix: "ea",
    statusField: "status",
    fields: [
      { key: "employee_id",    label: "Employee",      type: "text", required: true },
      { key: "asset",          label: "Asset",         type: "text", required: true },
      { key: "asset_tag",      label: "Asset Tag",     type: "text" },
      { key: "assigned_date",  label: "Assigned Date", type: "date", required: true },
      { key: "return_date",    label: "Return Date",   type: "date" },
      { key: "status",         label: "Status",        type: "select", options: ["Active", "Returned"] },
    ],
  },

  performance: {
    title: "Performance Management",
    storeKey: "performance",
    idPrefix: "pf",
    statusField: "rating",
    fields: [
      { key: "employee_id",   label: "Employee",       type: "text",   required: true },
      { key: "period",        label: "Review Period",  type: "text",   required: true },
      { key: "review_date",   label: "Review Date",    type: "date" },
      { key: "reviewer_id",   label: "Reviewer",       type: "text" },
      { key: "score",         label: "Score",          type: "number" },
      { key: "kpi_notes",     label: "KPI Notes",      type: "textarea" },
      { key: "rating",        label: "Rating",         type: "select", options: ["Excellent", "Good", "Average", "Poor"] },
      { key: "improvement_plan", label: "Improvement Plan", type: "textarea" },
    ],
    columns: ["employee_id", "period", "review_date", "score", "rating"],
  },

  recruitment: {
    title: "Recruitment",
    storeKey: "recruitment",
    idPrefix: "rc",
    statusField: "stage",
    fields: [
      { key: "name",        label: "Applicant Name",  type: "text",   required: true },
      { key: "position",    label: "Position",        type: "text",   required: true },
      { key: "department",label: "Department",     type: "text" },
      { key: "apply_date",  label: "Apply Date",      type: "date" },
      { key: "interview_date",label: "Interview Date",type: "date" },
      { key: "stage",       label: "Stage",           type: "select", options: ["Applied", "Screening", "Interview", "Offer", "Hired", "Rejected"] },
      { key: "status",      label: "Status",          type: "select", options: ["Active", "Closed"] },
      { key: "notes",       label: "Notes",           type: "textarea" },
    ],
    columns: ["name", "position", "department", "apply_date", "stage", "status"],
  },

  exits: {
    title: "Exit Management",
    storeKey: "exits",
    idPrefix: "ex",
    statusField: "clearance",
    fields: [
      { key: "employee_id",    label: "Employee",            type: "text",   required: true },
      { key: "exit_date",      label: "Exit Date",           type: "date",   required: true },
      { key: "reason",         label: "Reason",              type: "select", options: ["Resignation", "Termination", "Contract End", "Retirement"] },
      { key: "notice_given",   label: "Notice Given",        type: "select", options: ["true", "false"] },
      { key: "final_settlement",label: "Final Settlement",   type: "number" },
      { key: "clearance",      label: "Clearance",           type: "select", options: ["Pending", "In Progress", "Approved"] },
      { key: "notes",          label: "Notes",               type: "textarea" },
    ],
    columns: ["employee_id", "exit_date", "reason", "clearance"],
  },

  policies: {
    title: "HR Policies",
    storeKey: "policies",
    idPrefix: "pol",
    statusField: "status",
    fields: [
      { key: "title",    label: "Title",    type: "text", required: true },
      { key: "category", label: "Category", type: "text" },
      { key: "version",  label: "Version",  type: "text" },
      { key: "updated",  label: "Updated",  type: "date" },
      { key: "content",  label: "Content",  type: "textarea" },
      { key: "status",   label: "Status",   type: "select", options: ["Active", "Archived"] },
    ],
  },

  compensation: {
    title: "Compensation",
    storeKey: "compensation",
    idPrefix: "cp",
    fields: [
      { key: "employee_id",          label: "Employee",              type: "text",   required: true },
      { key: "grade",                label: "Grade / Band",          type: "text" },
      { key: "basic",                label: "Basic",                 type: "number", required: true },
      { key: "house_rent_allowance", label: "HRA",                   type: "number" },
      { key: "medical_allowance",    label: "Medical Allowance",     type: "number" },
      { key: "transport_allowance",  label: "Transport Allowance",   type: "number" },
      { key: "allowances",           label: "Other Allowances",      type: "number" },
      { key: "total",                label: "Total CTC",             type: "number" },
      { key: "effective_date",       label: "Effective Date",        type: "date" },
    ],
    columns: ["employee_id", "grade", "basic", "allowances", "total", "effective_date"],
  },

  // ─── FINANCE ─────────────────────────────────────────────────────────────

  accounts: {
    title: "Chart of Accounts",
    storeKey: "accounts",
    idPrefix: "acc",
    statusField: "is_active",
    fields: [
      { key: "account_code",    label: "Account Code",    type: "text",   required: true },
      { key: "account_name",    label: "Account Name",    type: "text",   required: true },
      { key: "parent_id",       label: "Parent Account",  type: "text" },
      { key: "account_type",    label: "Type",            type: "select", options: ["ASSET", "LIABILITY", "EQUITY", "REVENUE", "EXPENSE"], required: true },
      { key: "account_subtype", label: "Sub-Type",        type: "text" },
      { key: "normal_balance",  label: "Normal Balance",  type: "select", options: ["DEBIT", "CREDIT"], required: true },
      { key: "is_bank_account", label: "Bank Account",    type: "select", options: ["true", "false"] },
      { key: "is_cash_account", label: "Cash Account",    type: "select", options: ["true", "false"] },
      { key: "currency_code",   label: "Currency",        type: "text" },
      { key: "description",     label: "Description",     type: "textarea" },
      { key: "balance",         label: "Balance",         type: "number" },
      { key: "is_active",       label: "Status",          type: "select", options: ["true", "false"] },
    ],
    columns: ["account_code", "account_name", "account_type", "normal_balance", "balance", "is_active"],
  },

  invoices: {
    title: "Invoices",
    storeKey: "invoices",
    idPrefix: "inv",
    statusField: "status",
    fields: [
      { key: "invoice_number",    label: "Invoice #",         type: "text",   required: true },
      { key: "invoice_type",      label: "Type",              type: "select", options: ["SALES", "PURCHASE", "CREDIT_NOTE", "DEBIT_NOTE"], required: true },
      { key: "invoice_date",      label: "Invoice Date",      type: "date",   required: true },
      { key: "due_date",          label: "Due Date",          type: "date",   required: true },
      { key: "customer_id",       label: "Customer",          type: "text" },
      { key: "vendor_id",         label: "Vendor",            type: "text" },
      { key: "currency_code",     label: "Currency",          type: "text" },
      { key: "exchange_rate",     label: "Exchange Rate",     type: "number" },
      { key: "subtotal",          label: "Subtotal",          type: "number" },
      { key: "discount_type",     label: "Discount Type",     type: "select", options: ["PERCENT", "AMOUNT"] },
      { key: "discount_value",    label: "Discount Value",    type: "number" },
      { key: "tax_amount",        label: "Tax Amount",        type: "number" },
      { key: "total_amount",      label: "Total Amount",      type: "number" },
      { key: "paid_amount",       label: "Paid Amount",       type: "number" },
      { key: "outstanding_amount",label: "Outstanding",       type: "number" },
      { key: "notes",             label: "Notes",             type: "textarea" },
      { key: "terms",             label: "Payment Terms",     type: "textarea" },
      { key: "status",            label: "Status",            type: "select", options: ["DRAFT", "SENT", "PARTIAL", "PAID", "OVERDUE", "CANCELLED"] },
    ],
    columns: ["invoice_number", "invoice_type", "invoice_date", "due_date", "total_amount", "outstanding_amount", "status"],
  },

  expenses: {
    title: "Expenses",
    storeKey: "expenses",
    idPrefix: "exp",
    statusField: "status",
    fields: [
      { key: "category",      label: "Category",       type: "text",   required: true },
      { key: "date",          label: "Date",           type: "date",   required: true },
      { key: "amount",        label: "Amount",         type: "number", required: true },
      { key: "vendor",        label: "Vendor",         type: "text" },
      { key: "account_id",    label: "Account",        type: "text" },
      { key: "submitted_by",  label: "Submitted By",   type: "text" },
      { key: "approved_by",   label: "Approved By",    type: "text" },
      { key: "receipt_url",   label: "Receipt",        type: "text" },
      { key: "description",   label: "Description",    type: "textarea" },
      { key: "status",        label: "Status",         type: "select", options: ["DRAFT", "SUBMITTED", "Approved", "Paid", "Rejected", "Pending"] },
    ],
    columns: ["category", "date", "amount", "vendor", "submitted_by", "status"],
  },

  payables: {
    title: "Payables",
    storeKey: "payables",
    idPrefix: "pay",
    statusField: "status",
    fields: [
      { key: "vendor",       label: "Vendor",     type: "text",   required: true },
      { key: "invoice_ref",  label: "Invoice Ref",type: "text" },
      { key: "due",          label: "Due Date",   type: "date",   required: true },
      { key: "amount",       label: "Amount",     type: "number", required: true },
      { key: "paid_amount",  label: "Paid",       type: "number" },
      { key: "currency_code",label: "Currency",   type: "text" },
      { key: "status",       label: "Status",     type: "select", options: ["Pending", "Partial", "Paid", "Overdue"] },
    ],
    columns: ["vendor", "due", "amount", "paid_amount", "status"],
  },

  receivables: {
    title: "Receivables",
    storeKey: "receivables",
    idPrefix: "rec",
    statusField: "status",
    fields: [
      { key: "customer",     label: "Customer",   type: "text",   required: true },
      { key: "invoice_ref",  label: "Invoice Ref",type: "text" },
      { key: "due",          label: "Due Date",   type: "date",   required: true },
      { key: "amount",       label: "Amount",     type: "number", required: true },
      { key: "paid_amount",  label: "Paid",       type: "number" },
      { key: "currency_code",label: "Currency",   type: "text" },
      { key: "status",       label: "Status",     type: "select", options: ["Pending", "Partial", "Paid", "Overdue"] },
    ],
    columns: ["customer", "due", "amount", "paid_amount", "status"],
  },

  budgets: {
    title: "Budgets",
    storeKey: "budgets",
    idPrefix: "bg",
    statusField: "status",
    fields: [
      { key: "name",           label: "Budget Name",    type: "text",   required: true },
      { key: "budget_type",    label: "Type",           type: "select", options: ["ANNUAL", "QUARTERLY", "MONTHLY", "PROJECT"], required: true },
      { key: "department",     label: "Department",     type: "text",   required: true },
      { key: "period_start",   label: "Period Start",   type: "date",   required: true },
      { key: "period_end",     label: "Period End",     type: "date",   required: true },
      { key: "total_budgeted", label: "Budgeted",       type: "number", required: true },
      { key: "total_actual",   label: "Actual",         type: "number" },
      { key: "variance",       label: "Variance",       type: "number" },
      { key: "approved_by",    label: "Approved By",    type: "text" },
      { key: "status",         label: "Status",         type: "select", options: ["DRAFT", "APPROVED", "ACTIVE", "CLOSED"] },
      { key: "notes",          label: "Notes",          type: "textarea" },
    ],
    columns: ["name", "budget_type", "department", "total_budgeted", "total_actual", "variance", "status"],
  },

  bankAccounts: {
    title: "Bank & Cash",
    storeKey: "bankAccounts",
    idPrefix: "ba",
    fields: [
      { key: "bank",           label: "Bank Name",      type: "text",   required: true },
      { key: "account",        label: "Account #",      type: "text",   required: true },
      { key: "iban",           label: "IBAN",           type: "text" },
      { key: "branch",         label: "Branch",         type: "text" },
      { key: "account_type",   label: "Account Type",   type: "select", options: ["Current", "Savings", "Cash"] },
      { key: "currency_code",  label: "Currency",       type: "text" },
      { key: "balance",        label: "Balance",        type: "number" },
      { key: "is_active",      label: "Status",         type: "select", options: ["true", "false"] },
    ],
    columns: ["bank", "account", "branch", "account_type", "balance"],
  },

  financeAssets: {
    title: "Fixed Assets",
    storeKey: "financeAssets",
    idPrefix: "fa",
    statusField: "status",
    fields: [
      { key: "name",               label: "Asset Name",          type: "text",   required: true },
      { key: "category",           label: "Category",            type: "text" },
      { key: "purchase_date",      label: "Purchase Date",       type: "date" },
      { key: "cost_value",         label: "Cost Value",          type: "number" },
      { key: "depreciation_method",label: "Depreciation Method", type: "select", options: ["Straight-Line", "WDV"] },
      { key: "depreciation",       label: "Depreciation/Year",   type: "number" },
      { key: "accumulated_dep",    label: "Accumulated Dep.",    type: "number" },
      { key: "net_book_value",     label: "Net Book Value",      type: "number" },
      { key: "disposal_date",      label: "Disposal Date",       type: "date" },
      { key: "status",             label: "Status",              type: "select", options: ["Active", "Fully Depreciated", "Disposed"] },
    ],
    columns: ["name", "category", "cost_value", "depreciation", "net_book_value", "status"],
  },

  taxes: {
    title: "Taxes",
    storeKey: "taxes",
    idPrefix: "tx",
    fields: [
      { key: "name",       label: "Tax Name",   type: "text",   required: true },
      { key: "tax_type",   label: "Type",       type: "select", options: ["GST", "Sales Tax", "WHT", "Income Tax", "EOBI", "PESSI"] },
      { key: "rate",       label: "Rate (%)",   type: "number", required: true },
      { key: "period",     label: "Period",     type: "text" },
      { key: "amount",     label: "Amount",     type: "number" },
      { key: "account_id", label: "Account",    type: "text" },
      { key: "is_active",  label: "Status",     type: "select", options: ["true", "false"] },
    ],
    columns: ["name", "tax_type", "rate", "period", "amount"],
  },

  forecasts: {
    title: "Forecasting",
    storeKey: "forecasts",
    idPrefix: "fc",
    fields: [
      { key: "period",    label: "Period",    type: "text",   required: true },
      { key: "type",      label: "Type",      type: "select", options: ["REVENUE", "EXPENSE", "CASH_FLOW"] },
      { key: "revenue",   label: "Revenue",   type: "number" },
      { key: "expense",   label: "Expense",   type: "number" },
      { key: "profit",    label: "Profit",    type: "number" },
      { key: "actual",    label: "Actual",    type: "number" },
      { key: "variance",  label: "Variance",  type: "number" },
      { key: "notes",     label: "Notes",     type: "textarea" },
    ],
    columns: ["period", "type", "revenue", "expense", "profit", "actual", "variance"],
  },

  // ─── SETTINGS ─────────────────────────────────────────────────────────────

  users: {
    title: "Users & Roles",
    storeKey: "users",
    idPrefix: "u",
    statusField: "status",
    fields: [
      { key: "username",    label: "Username",   type: "text",   required: true },
      { key: "full_name",   label: "Full Name",  type: "text",   required: true },
      { key: "email",       label: "Email",      type: "text",   required: true },
      { key: "password",    label: "Password",   type: "text" },
      { key: "role",        label: "Role",       type: "select", options: ["COMPANY_ADMIN", "BRANCH_ADMIN", "STAFF"], required: true },
      { key: "department",   label: "Department", type: "select", options: ["HR", "INVENTORY", "FINANCE"], required: true },
      { key: "designation",   label: "Designation", type: "text" },
      { key: "branch_id",   label: "Branch",     type: "text" },
      { key: "employee_id", label: "Employee",   type: "text" },
      { key: "status",      label: "Status",     type: "select", options: ["Active", "Inactive"] },
    ],
    columns: ["username", "full_name", "email", "role", "department", "status"],
  },


  designations: {
    title: "Designations",
    storeKey: "designations",
    idPrefix: "dsg",
    fields: [
      { key: "title",        label: "Title",        type: "text",   required: true },
      { key: "department",label: "Department",   type: "select", options: ["HR", "INVENTORY", "FINANCE"], required: true },
      { key: "level",        label: "Level",        type: "select", options: ["Junior", "Mid", "Senior", "Lead", "Manager", "Director"] },
      { key: "pay_grade",    label: "Pay Grade",    type: "text" },
      { key: "is_active",    label: "Status",       type: "select", options: ["true", "false"] },
    ],
  },
  // ─── PERMISSIONS ──────────────────────────────────────────────────────────
  permissions: {
    title: "User Permissions",
    subtitle: "Manage access controls per user and module",
    storeKey: "permissions",
    idPrefix: "perm",
    fields: [
      { key: "user_id",           label: "User",              type: "select", required: true },
      { key: "module_name",       label: "Module",            type: "select", options: ["HR", "INVENTORY", "FINANCE", "SETTINGS"], required: true },
      { key: "feature_name",      label: "Feature/Page",      type: "text", required: true },
      { key: "is_create_access",  label: "Create Access",     type: "select", options: ["true", "false"] },
      { key: "is_update_access",  label: "Update Access",     type: "select", options: ["true", "false"] },
      { key: "is_delete_access",  label: "Delete Access",     type: "select", options: ["true", "false"] },
      { key: "is_view_access",    label: "View Access",       type: "select", options: ["true", "false"] },
    ],
    columns: ["user_id", "module_name", "feature_name", "is_create_access", "is_update_access", "is_delete_access", "is_view_access"],
  },
};