# Generated by Django 6.0.4 on 2026-05-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['short_name'], name='organizatio_short_n_ffac5e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_deleted'], name='organizatio_is_dele_d15430_idx'),
        ),
    ]
