# Generated by Django 6.0.4 on 2026-05-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
