# Generated by Django 6.0.4 on 2026-06-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_isfrom_user'),
        ('organization', '0002_alter_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isfrom_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='hr.employee'),
        ),
    ]
