/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppFinanceIndexRouteImport } from './routes/_app.finance.index'
import { Route as AppSettingsPreferencesRouteImport } from './routes/_app.settings.preferences'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppInventoryProductsRouteImport } from './routes/_app.inventory.products'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPreferencesRoute = AppSettingsPreferencesRouteImport.update({
  id: '/settings/preferences',
  path: '/settings/preferences',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/': typeof AppIndexRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/preferences': typeof AppSettingsPreferencesRoute
  '/finance': typeof AppFinanceIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inventory/products': typeof AppInventoryProductsRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/preferences': typeof AppSettingsPreferencesRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/inventory/products'
    | '/settings/company'
    | '/settings/preferences'
    | '/finance/'
    | '/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/'
    | '/inventory/products'
    | '/settings/company'
    | '/settings/preferences'
    | '/finance'
    | '/inventory'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/'
    | '/_app/inventory/products'
    | '/_app/settings/company'
    | '/_app/settings/preferences'
    | '/_app/finance/'
    | '/_app/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/preferences': {
      id: '/_app/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AppSettingsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsPreferencesRoute: typeof AppSettingsPreferencesRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsPreferencesRoute: AppSettingsPreferencesRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
