# Generated by Django 6.0.4 on 2026-06-06 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_salesorder_source'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='inventory.customer'),
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(choices=[('SALES_DESKTOP', 'Sales Desktop'), ('SALES_POS', 'Sales POS'), ('SALES_AGENT', 'Sales Agent')], db_index=True, default='SALES_DESKTOP', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
