# Generated by Django 6.0.4 on 2026-06-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_customerinvoice_due_date'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='converted_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='finance.customerinvoice'),
        ),
    ]
