# Generated by Django 6.0.4 on 2026-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_converted_invoice_to_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('TOO_EXPENSIVE', 'Too Expensive'), ('COMPETITOR_SELECTED', 'Competitor Selected'), ('NO_RESPONSE', 'No Response'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('FOLLOW_UP', 'Follow Up'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
