# Generated by Django 6.0.4 on 2026-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_lead_customer_quote_source_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FACEBOOK', 'Facebook'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
