# Generated by Django 6.0.4 on 2026-06-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_lead_source_lead_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('ACCEPTED', 'Accepted'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
