# Generated by Django 6.0.4 on 2026-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_lead_address_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
