# Generated by Django 6.0.4 on 2026-06-20 09:57

from django.db import migrations, models


def map_old_statuses(apps, schema_editor):
    Quote = apps.get_model('sales', 'Quote')
    status_map = {
        'ACCEPTED': 'APPROVED',
        'DECLINED': 'REJECTED',
        'EXPIRED': 'REJECTED',
    }
    for old, new in status_map.items():
        Quote.objects.filter(status=old).update(status=new)


def reverse_map(apps, schema_editor):
    Quote = apps.get_model('sales', 'Quote')
    status_map = {
        'APPROVED': 'ACCEPTED',
        'REJECTED': 'DECLINED',
    }
    for new, old in status_map.items():
        Quote.objects.filter(status=new).update(status=old)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_increase_phone_length'),
    ]

    operations = [
        migrations.RunPython(map_old_statuses, reverse_map),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CONVERTED', 'Converted to Invoice')], default='DRAFT', max_length=20),
        ),
    ]
