# Generated by Django 6.0.4 on 2026-06-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variantimage_image_url_thumb'),
        ('sales', '0006_update_quote_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='inventory.customer'),
        ),
    ]
