# Generated by Django 6.0.4 on 2026-06-27 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variantimage_image_url_thumb'),
        ('sales', '0007_lead_converted_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='is_manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='manual_variant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='manual_variant_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quoteline',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='inventory.productvariant'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['vendor'], name='sales_quote_vendor__b57d49_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteline',
            index=models.Index(fields=['is_manual_entry'], name='sales_quote_is_manu_6b8dd3_idx'),
        ),
    ]
