# Generated by Django 6.0.4 on 2026-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_quote_overall_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
