# Generated by Django 6.0.4
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0010_quoteline_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entity_type', models.CharField(choices=[('LEAD', 'Lead'), ('QUOTE', 'Quote')], db_index=True, max_length=10)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesstatushistory_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesstatushistory_updated', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesstatushistory_deleted', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_status_history',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['entity_type', 'entity_id'], name='sales_status_entity_idx'),
                    models.Index(fields=['company_id', 'branch_id'], name='sales_status_company_idx'),
                ],
            },
        ),
    ]
