# Generated by Django 6.0.4 on 2026-07-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_lead_priority'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='sales_leads_priorit_7cc57c_idx',
            old_name='sales_leads_priority_idx',
        ),
    ]
